package dk.dbc.dataio.flowstore.entity;

import dk.dbc.dataio.flowstore.util.json.JsonException;
import org.codehaus.jackson.annotate.JsonRawValue;

import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.MappedSuperclass;

/**
 * Base class for flow store entities where id is auto
 * generated by the underlying store and the data content is
 * given as JSON string
 */
@MappedSuperclass
public class Entity {
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @Lob
    @Column(nullable = false)
    private String content;

    public Long getId() {
        return id;
    }

    @JsonRawValue
    public String getContent() {
        return content;
    }

    /**
     * Sets data content as JSON string while extracting special
     * index values
     *
     * @param content flow data as JSON string
     *
     * @throws JsonException when given invalid (null-valued, empty-valued or non-json)
     *                       JSON string, or if JSON object does not contain 'name'
     *                       member with non-empty text value
     */
    public void setContent(String content) throws JsonException {
        extractIndexValuesFromContent(content);
        this.content = content;
    }

    /**
     * Extracts necessary index values from given data
     *
     * @param data entity content
     *
     * @throws JsonException on failure to extract value from json data
     */
    protected void extractIndexValuesFromContent(String data) throws JsonException { }
}
