package dk.dbc.dataio.flowstore.entity;

import org.codehaus.jackson.annotate.JsonIgnore;
import org.codehaus.jackson.annotate.JsonRawValue;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Persistence domain class for flow objects where id is auto
 * generated by the underlying store and the data content is
 * given as JSON string
 */
@Entity
@Table(name="flows")
public class Flow {
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    private Long id;

    @Column(columnDefinition="TEXT NOT NULL")
    private String data;

    @Column(name="flowname_idx", columnDefinition="TEXT NOT NULL UNIQUE")
    private String flownameIndexValue;

    public Long getId() {
        return id;
    }

    @JsonRawValue
    public String getData() {
        return data;
    }

    public void setData(String data) {
        this.data = data;
    }

    @JsonIgnore
    public String getFlownameIndexValue() {
        return flownameIndexValue;
    }

    public void setFlownameIndexValue(String flownameIndexValue) {
        this.flownameIndexValue = flownameIndexValue;
    }
}
