/*
 * DataIO - Data IO
 * Copyright (C) 2015 Dansk Bibliotekscenter a/s, Tempovej 7-11, DK-2750 Ballerup,
 * Denmark. CVR: 15149043
 *
 * This file is part of DataIO.
 *
 * DataIO is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * DataIO is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with DataIO.  If not, see <http://www.gnu.org/licenses/>.
 */

package dk.dbc.dataio.flowstore.entity;

import com.fasterxml.jackson.annotation.JsonRawValue;
import dk.dbc.dataio.commons.types.FlowComponentContent;
import dk.dbc.dataio.commons.utils.json.JsonException;
import dk.dbc.dataio.commons.utils.json.JsonUtil;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Index;
import javax.persistence.Lob;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Persistence domain class for flow component objects where id is auto
 * generated by the underlying store and the data content is
 * given as JSON string
 */
@Entity
@Table(name = FlowComponent.TABLE_NAME,
    uniqueConstraints = {
        @UniqueConstraint(columnNames = { FlowComponent.NAME_INDEX_COLUMN })
    },
    indexes = @Index(columnList = FlowComponent.NAME_INDEX_COLUMN)
)
@NamedQueries({
    @NamedQuery(name = FlowComponent.QUERY_FIND_ALL, query = "SELECT component FROM FlowComponent component ORDER BY component.nameIndexValue ASC")
})
public class FlowComponent extends VersionedEntity {
    public static final String TABLE_NAME = "flow_components";
    public static final String QUERY_FIND_ALL = "FlowComponent.findAll";
    static final String NAME_INDEX_COLUMN = "name_idx";

    @Lob
    @Column(name = NAME_INDEX_COLUMN, nullable = false)
    private String nameIndexValue;

    @Lob
    private String next;

    String getNameIndexValue() {
        return nameIndexValue;
    }

    @JsonRawValue
    public String getNext() {
        return next;
    }

    public void setNext(String next) {
        if(next!= null) {
            this.next = next.isEmpty() ? null : next;
        }
    }

    /**
     * {@inheritDoc}
     * @throws NullPointerException if given null-valued data argument
     * @throws IllegalArgumentException if given empty-valued data argument
     * @throws JsonException if non-json JSON string or if given JSON is invalid FlowComponentContent.
     */
    @Override
    protected void preProcessContent(String data) throws JsonException {
        final FlowComponentContent flowComponentContent = JsonUtil.fromJson(data, FlowComponentContent.class);
        nameIndexValue = flowComponentContent.getName();
    }
}
