/*
 * DataIO - Data IO
 * Copyright (C) 2015 Dansk Bibliotekscenter a/s, Tempovej 7-11, DK-2750 Ballerup,
 * Denmark. CVR: 15149043
 *
 * This file is part of DataIO.
 *
 * DataIO is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * DataIO is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with DataIO.  If not, see <http://www.gnu.org/licenses/>.
 */

package dk.dbc.dataio.flowstore.entity;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

/**
 * Persistence domain class for gatekeeperDestination objects where id is auto
 * generated by the underlying store
 */
@Entity
@Table(name = "gatekeeper_destinations")
@NamedQueries({
        @NamedQuery(name = GatekeeperDestinationEntity.QUERY_FIND_ALL, query = "SELECT gatekeeperDestinationEntity FROM GatekeeperDestinationEntity gatekeeperDestinationEntity ORDER BY gatekeeperDestinationEntity.submitterNumber ASC")
})

public class GatekeeperDestinationEntity {

    public static final String QUERY_FIND_ALL = "GatekeeperDestinationEntity.findAll";

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private int id;
    private String submitterNumber;
    private String destination;
    private String packaging;
    private String format;

    public GatekeeperDestinationEntity() {}

    public int getId() {
        return id;
    }

    public String getSubmitterNumber() {
        return submitterNumber;
    }

    public void setSubmitterNumber(String submitterNumber) {
        this.submitterNumber = submitterNumber;
    }

    public String getDestination() {
        return destination;
    }

    public void setDestination(String destination) {
        this.destination = destination;
    }

    public String getPackaging() {
        return packaging;
    }

    public void setPackaging(String packaging) {
        this.packaging = packaging;
    }

    public String getFormat() {
        return format;
    }

    public void setFormat(String format) {
        this.format = format;
    }
}
