package dk.dbc.dataio.flowstore.entity;

import dk.dbc.commons.jsonb.JSONBContext;
import dk.dbc.commons.jsonb.JSONBException;
import dk.dbc.dataio.commons.types.SubmitterContent;

import javax.persistence.Entity;
import javax.persistence.EntityResult;
import javax.persistence.NamedNativeQueries;
import javax.persistence.NamedNativeQuery;
import javax.persistence.SqlResultSetMapping;
import javax.persistence.SqlResultSetMappings;
import javax.persistence.Table;


/**
 * Persistence domain class for submitter objects where id is auto
 * generated by the underlying store and the data content is
 * given as JSON string
 */
@Entity
@Table(name = Submitter.TABLE_NAME)
@SqlResultSetMappings(
        @SqlResultSetMapping(name = "Submitter.implicit", entities = {
                @EntityResult(entityClass = Submitter.class)})
)
@NamedNativeQueries({
        @NamedNativeQuery(
                name = Submitter.QUERY_FIND_ALL,
                query = "SELECT * FROM "+Submitter.TABLE_NAME+" ORDER BY (content->>'number')::BIGINT ASC",
                resultSetMapping = "Submitter.implicit"
        ),
        @NamedNativeQuery(
                name = Submitter.QUERY_FIND_ALL_IDS,
                query = "SELECT id FROM "+Submitter.TABLE_NAME
        ),
        @NamedNativeQuery(
                name = Submitter.QUERY_FIND_BY_CONTENT,
                query = "SELECT * FROM "+Submitter.TABLE_NAME+" WHERE content @> ?::jsonb",
                resultSetMapping = "Submitter.implicit"
        )
})
public class Submitter extends Versioned {
    public static final String TABLE_NAME = "submitters";
    public static final String QUERY_FIND_ALL = "Submitter.findAll";
    public static final String QUERY_FIND_ALL_IDS = "Submitter.findAllIds";
    public static final String QUERY_FIND_BY_CONTENT = "Submitter.findByContent";

    /**
     * {@inheritDoc}
     * @throws NullPointerException if given null-valued data argument
     * @throws IllegalArgumentException if given empty-valued data argument
     * @throws JSONBException if non-json JSON string or if given JSON is invalid SubmitterContent
     */
    @Override
    public void setContent(String data) throws JSONBException {
        super.setContent(data);
        new JSONBContext().unmarshall(data, SubmitterContent.class);
    }
}
