package dk.dbc.dataio.flowstore.entity;

import com.fasterxml.jackson.annotation.JsonRawValue;

import javax.persistence.Column;
import javax.persistence.Convert;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.MappedSuperclass;
import javax.persistence.Version;

/**
 * Base class for flow store entities where id is auto
 * generated by the underlying store and the data content is
 * given as JSON string
 */
@MappedSuperclass
public class Versioned {
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @Version
    @Column(nullable = false)
    private Long version;

    @Lob
    @Column(nullable = false, columnDefinition = "json")
    @Convert(converter = JsonConverter.class)
    private String content;

    public Long getId() {
        return id;
    }

    public Long getVersion() {
        return version;
    }

    public void setVersion(Long version) {
        this.version = version;
    }

    @JsonRawValue
    public String getContent() {
        return content;
    }

    /**
     * Sets entity data content as JSON string
     *
     * @param content entity data as JSON string
     */
    public void setContent(String content) {
        this.content = content;
    }
}
