/*
 * DataIO - Data IO
 * Copyright (C) 2015 Dansk Bibliotekscenter a/s, Tempovej 7-11, DK-2750 Ballerup,
 * Denmark. CVR: 15149043
 *
 * This file is part of DataIO.
 *
 * DataIO is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * DataIO is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with DataIO.  If not, see <http://www.gnu.org/licenses/>.
 */

package dk.dbc.dataio.filestore.service.entity;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonRawValue;
import dk.dbc.dataio.commons.utils.invariant.InvariantUtil;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Date;

/**
 * Persistence domain class for file attributes objects where id is auto
 * generated by the underlying store
 */
@Entity
@Table(name = FileAttributes.TABLE_NAME)
public class FileAttributes {
    public static final String TABLE_NAME = "file_attributes";

    FileAttributes() { }

    /**
     * Class constructor
     * @param creationTime file creation time
     * @param path file location in store
     * @throws NullPointerException if given null-valued creationTime or path argument
     * @throws IllegalArgumentException if given empty path
     */
    public FileAttributes(Date creationTime, Path path)
            throws NullPointerException, IllegalArgumentException {
        this.creationTime = new Date(InvariantUtil.checkNotNullOrThrow(creationTime, "creationTime").getTime());
        InvariantUtil.checkNotNullOrThrow(path, "path");
        location = InvariantUtil.checkNotNullNotEmptyOrThrow(path.toString(), "path");
    }

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @Temporal(TemporalType.TIMESTAMP)
    private Date creationTime;

    @JsonIgnore
    private String location;

    private long byteSize;

    @JsonRawValue
    private String metadata;

    public Long getId() {
        return id;
    }

    public Date getCreationTime() {
        return new Date(creationTime.getTime());
    }

    public Path getLocation() {
        return Paths.get(location);
    }

    public void setByteSize(long byteSize) {
        this.byteSize = byteSize;
    }

    public long getByteSize() {
        return byteSize;
    }

    public String getMetadata() {
        return metadata;
    }

    public void setMetadata(String metadata) {
        this.metadata = metadata;
    }
}
