[template]
src = "db-connection-pools.xml.tmpl"
dest = "/home/gfish/dbc-payara.d/19-db-connection-pools.xml"

keys = [
    "/dbc/postgres/harvester/ush/env/postgres/host",
    "/dbc/postgres/harvester/ush/env/postgres/user",
    "/dbc/postgres/harvester/ush/env/postgres/password",
    "/dbc/harvester/ush/env/postgres/db"
]
