DELETE FROM harvester_configs CASCADE;
DELETE FROM flow_binders CASCADE;
DELETE FROM flows CASCADE;
DELETE FROM flow_components CASCADE;
DELETE FROM sinks;
INSERT INTO harvester_configs (id, version, type, content) VALUES (1, 1, 'dk.dbc.dataio.harvester.types.RRHarvesterConfig', '{"id": "broend-sync", "format": "katalog", "resource": "jdbc/dataio/rawrepo", "batchSize": 10000, "enabled": false, "consumerId": "broend-sync", "destination": "broend3", "formatOverrides": {"870970": "basis"}, "includeRelations": true}');
INSERT INTO harvester_configs (id, version, type, content) VALUES (2, 1, 'dk.dbc.dataio.harvester.types.RRHarvesterConfig', '{"id": "broend-sync-loadtest", "type": "TEST", "format": "katalog", "resource": "jdbc/dataio/rawrepo", "batchSize": 50000, "enabled": true, "consumerId": "broend-loadtest-sync", "destination": "broend3-loadtest", "formatOverrides": {"870970": "basis"}, "includeRelations": true}');
INSERT INTO harvester_configs (id, version, type, content) VALUES (3, 1, 'dk.dbc.dataio.harvester.types.RRHarvesterConfig', '{"id": "XMLDOM-sync", "format": "katalog", "resource": "jdbc/dataio/rawrepo", "batchSize": 10000, "enabled": true, "consumerId": "XMLDOM-sync", "destination": "XMLDOM", "formatOverrides": {"870970": "basis"}, "includeRelations": true}');
INSERT INTO harvester_configs (id, version, type, content) VALUES (4, 1, 'dk.dbc.dataio.harvester.types.RRHarvesterConfig', '{"id": "E4X-sync", "format": "katalog", "resource": "jdbc/dataio/rawrepo", "batchSize": 10000, "enabled": true, "consumerId": "E4X-sync", "destination": "E4X", "formatOverrides": {"870970": "basis"}, "includeRelations": true}');
INSERT INTO harvester_configs (id, version, type, content) VALUES (5, 1, 'dk.dbc.dataio.harvester.types.RRHarvesterConfig', '{"id": "basis-decentral", "format": "basis", "resource": "jdbc/dataio/rawrepo", "batchSize": 10000, "enabled": true, "consumerId": "basis-decentral", "destination": "basis", "formatOverrides": {"870970": "basis"}, "includeRelations": true}');
INSERT INTO harvester_configs (id, version, type, content) VALUES (6, 1, 'dk.dbc.dataio.harvester.types.RRHarvesterConfig', '{"id": "broend-sync-exttest", "format": "katalog", "resource": "jdbc/dataio/rawrepo-exttest", "batchSize": 10000, "enabled": false, "consumerId": "broend-sync", "destination": "broend3-exttest", "formatOverrides": {"870970": "basis"}, "includeRelations": true}');

INSERT INTO sinks(id, content, version) VALUES ( 1, '{"name": "sink-1", "queue": "queue", "timeout": 1, "sinkType": "DUMMY", "sinkConfig": null, "description": "description", "sequenceAnalysisOption": "ALL"}',1);


INSERT INTO flow_components(id, content, version, view) VALUES (2,  '{"name": "fc-1"}', 1, '{}');

INSERT INTO flows (id, content, version, view) VALUES (1, '{"name": "ParameterSuggester", "components": [{"id": 1212, "next": null, "content": {"name": "FlowComponentsIT.deleteFlowComponentReferencedByFlow.component", "description": "description", "javascripts": [{"javascript": "javascript", "moduleName": "moduleName"}], "svnRevision": 1, "requireCache": null, "invocationMethod": "invocationMethod", "invocationJavascriptName": "invocationJavascriptName", "svnProjectForInvocationJavascript": "svnprojectforinvocationjavascript"}, "version": 1}], "description": "description"}', 1, '{}');

INSERT INTO flow_binders(id, content, version, flow_id, sink_id) VALUES (1,'{"name": "ParameterSuggester-1", "flowId": 1, "format": "format-1", "sinkId": 1, "charset": "utf-8", "priority": "NORMAL", "packaging": "iso", "description": "flowbinder-description", "destination": "destination-1", "submitterIds": [1219], "queueProvider": "queue-provider", "recordSplitter": "XML"}', 1, 1, 1);
INSERT INTO flow_binders(id, content, version, flow_id, sink_id) VALUES (2,'{"name": "ParameterSuggester-2", "flowId": 1, "format": "format-2", "sinkId": 1, "charset": "utf-16", "priority": "NORMAL", "packaging": "XML", "description": "flowbinder-description", "destination": "destination-2", "submitterIds": [1219], "queueProvider": "queue-provider", "recordSplitter": "XML"}', 1, 1, 1);
INSERT INTO flow_binders(id, content, version, flow_id, sink_id) VALUES (3,'{"name": "ParameterSuggester-3", "flowId": 1, "format": "format-3", "sinkId": 1, "charset": "utf-128", "priority": "NORMAL", "packaging": "json", "description": "flowbinder-description", "destination": "destination-3", "submitterIds": [1219], "queueProvider": "queue-provider", "recordSplitter": "XML"}', 1, 1, 1);
INSERT INTO flow_binders(id, content, version, flow_id, sink_id) VALUES (4,'{"name": "ParameterSuggester-4", "flowId": 1, "format": "format-3", "sinkId": 1, "charset": "utf-128", "priority": "NORMAL", "packaging": "json", "description": "flowbinder-description", "destination": "destination-3", "submitterIds": [1219], "queueProvider": "queue-provider", "recordSplitter": "XML"}', 1, 1, 1);
