#!/usr/bin/env bash

# HERE BE DRAGONS!
#
# Due to the XML plenary decision to deprecate the use of relative URIs in namespace declarations (things like
# xmlns:foo="../bar") for C14n canonicalization causes xmllint to fail the marcXchange namespace URI
# info:lc/xmlns/marcxchange-v1 as a relative namespace.
#
# (See also https://www.w3.org/TR/2001/REC-xml-c14n-20010315)
#
# Current somewhat scary work-around is to insert the string 'urn:' before all namespace URIs starting with info:

display_help() {
    echo "Usage: xmldiff XML_DOC1 XML_DOC2 [DIFF_OPTION]..." >&2
    echo "Compare C14n normalized versions of XML documents XML_DOC1 and XML_DOC2"
    echo "   -h                         Show this help"
    echo "   [DIFF_OPTION]              Any option supported by the diff command"
}

if [ "$#" -lt 2 ] || [ "$1" == "-h" ]; then
    display_help
    exit 0
fi

DIFF_TOOL="${DIFF_TOOL:-diff}"

OPTIONS=${@:3}
if grep -vq -e '\-\-side-by-side' -e '\-U ' -e '\-\-unified' -e '\-C ' -e '\-\-context' <<<${OPTIONS}; then
    OPTIONS+=' -U 10000'
fi

${DIFF_TOOL} <(cat $1 | sed 's/ xmlns="\([^"]*\)"/ xmlns="urn:\1"/g' \
                   | sed 's/ xmlns:\([^=]*\)="\([^"]*\)"/ xmlns:\1="urn:\2"/g' \
                   | xmllint --exc-c14n - \
                   | xmllint --format --encode utf8 -) \
          <(cat $2 | sed 's/ xmlns="\([^"]*\)"/ xmlns="urn:\1"/g' \
                   | sed 's/ xmlns:\([^=]*\)="\([^"]*\)"/ xmlns:\1="urn:\2"/g' \
                   | xmllint --exc-c14n - \
                   | xmllint --format --encode utf8 -) \
          ${OPTIONS}
