
package dk.dbc.oss.ns.updatemarcxchange;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import java.util.List;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UpdateMarcXchangePortType", targetNamespace = "http://oss.dbc.dk/ns/updateMarcXchange")
@XmlSeeAlso({
    dk.dbc.oss.ns.updatemarcxchange.ObjectFactory.class,
    info.lc.xmlns.marcxchange_v1.ObjectFactory.class
})
public interface UpdateMarcXchangePortType {


    /**
     * 
     * @param updateMarcXchangeRequest
     * @return
     *     returns java.util.List<dk.dbc.oss.ns.updatemarcxchange.UpdateMarcXchangeResult>
     */
    @WebMethod(action = "http://oss.dbc.dk/ns/updateMarcXchange/UpdateMarcXchange")
    @WebResult(name = "updateMarcXchangeResult", targetNamespace = "http://oss.dbc.dk/ns/updateMarcXchange")
    @RequestWrapper(localName = "updateMarcXchange", targetNamespace = "http://oss.dbc.dk/ns/updateMarcXchange", className = "dk.dbc.oss.ns.updatemarcxchange.UpdateMarcXchange")
    @ResponseWrapper(localName = "updateMarcXchangeResponse", targetNamespace = "http://oss.dbc.dk/ns/updateMarcXchange", className = "dk.dbc.oss.ns.updatemarcxchange.UpdateMarcXchangeResponse")
    public List<UpdateMarcXchangeResult> updateMarcXchange(
        @WebParam(name = "updateMarcXchangeRequest", targetNamespace = "http://oss.dbc.dk/ns/updateMarcXchange")
        UpdateMarcXchangeRequest updateMarcXchangeRequest);

}
