
package dk.dbc.oss.ns.updatemarcxchange;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "UpdateMarcXchangePortType", targetNamespace = "http://oss.dbc.dk/ns/updateMarcXchange")
@XmlSeeAlso({
    dk.dbc.oss.ns.updatemarcxchange.ObjectFactory.class,
    info.lc.xmlns.marcxchange_v1.ObjectFactory.class
})
public interface UpdateMarcXchangePortType {


    /**
     * 
     * @param updateMarcXchangeRequest
     * @return
     *     returns java.util.List<dk.dbc.oss.ns.updatemarcxchange.UpdateMarcXchangeResult>
     */
    @WebMethod(action = "http://oss.dbc.dk/ns/updateMarcXchange/UpdateMarcXchange")
    @WebResult(name = "updateMarcXchangeResult", targetNamespace = "http://oss.dbc.dk/ns/updateMarcXchange")
    @RequestWrapper(localName = "updateMarcXchange", targetNamespace = "http://oss.dbc.dk/ns/updateMarcXchange", className = "dk.dbc.oss.ns.updatemarcxchange.UpdateMarcXchange")
    @ResponseWrapper(localName = "updateMarcXchangeResponse", targetNamespace = "http://oss.dbc.dk/ns/updateMarcXchange", className = "dk.dbc.oss.ns.updatemarcxchange.UpdateMarcXchangeResponse")
    public List<UpdateMarcXchangeResult> updateMarcXchange(
        @WebParam(name = "updateMarcXchangeRequest", targetNamespace = "http://oss.dbc.dk/ns/updateMarcXchange")
        UpdateMarcXchangeRequest updateMarcXchangeRequest);

}
