
package dk.dbc.oss.ns.updatemarcxchange;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "UpdateMarcXchangeServices", targetNamespace = "http://oss.dbc.dk/ns/updateMarcXchange", wsdlLocation = "http://localhost/wsdl/updateMarcXchange.wsdl")
public class UpdateMarcXchangeServices
    extends Service
{

    private static final URL UPDATEMARCXCHANGESERVICES_WSDL_LOCATION;
    private static final WebServiceException UPDATEMARCXCHANGESERVICES_EXCEPTION;
    private static final QName UPDATEMARCXCHANGESERVICES_QNAME = new QName("http://oss.dbc.dk/ns/updateMarcXchange", "UpdateMarcXchangeServices");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost/wsdl/updateMarcXchange.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        UPDATEMARCXCHANGESERVICES_WSDL_LOCATION = url;
        UPDATEMARCXCHANGESERVICES_EXCEPTION = e;
    }

    public UpdateMarcXchangeServices() {
        super(__getWsdlLocation(), UPDATEMARCXCHANGESERVICES_QNAME);
    }

    public UpdateMarcXchangeServices(WebServiceFeature... features) {
        super(__getWsdlLocation(), UPDATEMARCXCHANGESERVICES_QNAME, features);
    }

    public UpdateMarcXchangeServices(URL wsdlLocation) {
        super(wsdlLocation, UPDATEMARCXCHANGESERVICES_QNAME);
    }

    public UpdateMarcXchangeServices(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, UPDATEMARCXCHANGESERVICES_QNAME, features);
    }

    public UpdateMarcXchangeServices(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UpdateMarcXchangeServices(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns UpdateMarcXchangePortType
     */
    @WebEndpoint(name = "UpdateMarcXchangePort")
    public UpdateMarcXchangePortType getUpdateMarcXchangePort() {
        return super.getPort(new QName("http://oss.dbc.dk/ns/updateMarcXchange", "UpdateMarcXchangePort"), UpdateMarcXchangePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UpdateMarcXchangePortType
     */
    @WebEndpoint(name = "UpdateMarcXchangePort")
    public UpdateMarcXchangePortType getUpdateMarcXchangePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://oss.dbc.dk/ns/updateMarcXchange", "UpdateMarcXchangePort"), UpdateMarcXchangePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (UPDATEMARCXCHANGESERVICES_EXCEPTION!= null) {
            throw UPDATEMARCXCHANGESERVICES_EXCEPTION;
        }
        return UPDATEMARCXCHANGESERVICES_WSDL_LOCATION;
    }

}
