#!/bin/bash

BASEDIR=$(cd "$(dirname "$0")"; pwd)

function startup {
    # Starts postgresql. h2 and glassfish
    ${BASEDIR}/integration-test/postgresql/bin/start_postgresql
    ${BASEDIR}/integration-test/h2/bin/start_h2
    ${BASEDIR}/integration-test/glassfish/bin/start_glassfish4
}

function shutdown {
    # Stops postgresql, h2 and glassfish
    ${BASEDIR}/integration-test/glassfish/bin/stop_glassfish4
    ${BASEDIR}/integration-test/h2/bin/stop_h2
    ${BASEDIR}/integration-test/postgresql/bin/stop_postgresql
    rm -r ${BASEDIR}/integration-test/mountpoint/*
}

function deploy {
    mvn -f ${BASEDIR}/pom.xml -P dev -pl integration-test/gui-selenium -am package org.codehaus.cargo:cargo-maven2-plugin:deploy
}

function undeploy {
    mvn -f ${BASEDIR}/pom.xml -P dev -pl integration-test/gui-selenium -DskipTests -am package org.codehaus.cargo:cargo-maven2-plugin:undeploy
}

trap shutdown SIGHUP SIGINT SIGTERM

legal_parameters="start stop startup shutdown"

[[ $legal_parameters =~ $1 ]] && echo "" || echo "$1 is an illegal parameter. Legal parameters are 'start' and 'stop'"

case $1 in
    start) 
	startup
	deploy
	;;
    startup) 
	startup
	;;
    stop)
	undeploy
	shutdown
	;;
    shutdown)
	shutdown
	;;
esac
