#!/bin/bash -e

BASEDIR=$(cd "$(dirname "$0")"; pwd)

function startup {
    clear_mountpoint
    # Starts postgresql. h2 and glassfish
    ${BASEDIR}/integration-test/postgresql/bin/start_postgresql
    ${BASEDIR}/integration-test/h2/bin/start_h2
    ${BASEDIR}/integration-test/glassfish/bin/start_glassfish4
}

function shutdown {
    # Stops postgresql, h2 and glassfish
    ${BASEDIR}/integration-test/glassfish/bin/stop_glassfish4
    ${BASEDIR}/integration-test/h2/bin/stop_h2
    ${BASEDIR}/integration-test/postgresql/bin/stop_postgresql
    clear_mountpoint
}

function developmentmode {
    startup
    # setting up JNDI endpoints
    echo "setting up JNDI endpoints for staging..."
    ENDPOINTDIR=${BASEDIR}/integration-test/glassfish/jndioverrides
    # for f in `find ${ENDPOINTDIR} -type f -executable` ; do
    #   echo "JNDI endpoints changes is run from " $( basename ${f})
    #   ${f}
    #done
    echo "JNDI endpoints changes is run from " ${ENDPOINTDIR}
    ${ENDPOINTDIR}/glassfish4_add_endpoints
    echo "JNDI settings configured."
}

function deploy {
    echo Dont know how to deploy
}

function undeploy {
   echo Dont know hot to undeploy
}

function clear_mountpoint {
    rm -rf ${BASEDIR}/integration-test/mountpoint/*
}

trap shutdown SIGHUP SIGINT SIGTERM

legal_parameters="start stop devmode help"

[[ $legal_parameters =~ $1 ]] && echo "" || echo "$1 is an illegal parameter. Legal parameters are : $legal_parameters"

arg=$1
if [ -z "$arg" ] ; then
   arg=start
fi

arg1=$1
if [ "$arg1" = devmode ] ; then
    arg1=devmode
fi

case $arg in
    start) 
	startup
	;;
    stop)
	shutdown
	;;
	devmode)
	developmentmode
	;;
    help)
	echo "usage $0 [command]"
	echo "  command must be on of the following"
	echo "   - start    : startup + deploy dataio components"
	echo "   - devmode  : startup + deploy dataio components + JNDI endpoints against staging"
	echo "   - startup  : start databases and glassfish"
	echo "   - stop     : shutdown + undeploy dataio components"
	echo "   - shutdown : stop databases and glassfish"
	;;
    *)
	echo Missing/Unknown argument Must be one of : $legal_parameters
	;;
esac
