#!/bin/bash

BASEDIR=$(cd "$(dirname "$0")"; pwd)

function startup {
    # Starts h2 and glassfish
    $BASEDIR/integration-test/h2/bin/start_h2
    $BASEDIR/integration-test/glassfish/bin/start_glassfish4
}

function shutdown {
    # Stops h2 and glassfish
    $BASEDIR/integration-test/glassfish/bin/stop_glassfish4
    $BASEDIR/integration-test/h2/bin/stop_h2
}

function deploy {
    mvn -f $BASEDIR/pom.xml -P dev -pl integration-test/gui-selenium -am package cargo:deploy
}

function undeploy {
    mvn -f $BASEDIR/pom.xml -P dev -pl integration-test/gui-selenium -DskipTests -am package cargo:undeploy
}

trap shutdown SIGHUP SIGINT SIGTERM

legal_parameters="start stop"

[[ $legal_parameters =~ $1 ]] && echo "" || echo "$1 is an illegal parameter. Legal parameters are 'start' and 'stop'"

case $1 in
    start) 
	startup
	deploy
	;;
    stop)
	undeploy
	shutdown
	;;
esac

	