ALTER TABLE block ADD COLUMN itemId INTEGER NOT NULL DEFAULT 0;
ALTER TABLE block DROP CONSTRAINT block_pkey;
ALTER TABLE block ADD PRIMARY KEY (jobId, chunkId, itemId);
ALTER TABLE block ALTER COLUMN itemId DROP DEFAULT;
