startDelaySeconds: 0
#hostPort: 127.0.0.1:1234
#username:
#password:
jmxUrl: service:jmx:rmi:///jndi/rmi://${JMX_HOST}/jmxrmi
ssl: false
lowercaseOutputName: false
lowercaseOutputLabelNames: false
whitelistObjectNames: ["dbc:*.*", "java.lang:type=Memory", "java.lang:type=OperatingSystem"]

rules:
  - pattern: "^.*?<:*?type=(\\w*)(?:,name=(\\*))?><>(.*)"
    attrNameSnakeCase: true
    name: $3
    labels:
      type: $1
      name: $2
