startDelaySeconds: 0
#hostPort: 127.0.0.1:1234
#username:
#password:
jmxUrl: service:jmx:rmi:///jndi/rmi://${JMX_HOST}/jmxrmi
ssl: false
lowercaseOutputName: false
lowercaseOutputLabelNames: false
whitelistObjectNames: ["dbc:*", "java.lang:type=Memory", "java.lang:type=OperatingSystem"]

rules:
  - pattern: "java.lang<type=(\\w+)><>(\\w+)"
    attrNameSnakeCase: true
    name: $2
    labels:
      type: $1
  - pattern: "dbc<.*name=(\\w+)><>(.*)"
    attrNameSnakeCase: true
    name: $1
