[template]
src = "db-connection-pools.xml.tmpl"
dest = "/home/gfish/dbc-payara.d/19-db-connection-pools.xml"

keys = [
  "/dbc/postgres/logstore/env/postgres/password",
  "/dbc/postgres/logstore/env/postgres/user",
  "/dbc/postgres/logstore/env/postgres/db"
]
