
package dk.dbc.oclc.wciru;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "updateInterface", targetNamespace = "http://Update.os.oclc.ORG")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UpdateInterface {


    /**
     * 
     * @param updateRequest
     * @return
     *     returns dk.dbc.oclc.wciru.UpdateResponseType
     */
    @WebMethod
    @WebResult(name = "updateResponse", targetNamespace = "http://www.loc.gov/zing/srw/update/", partName = "updateResponse")
    public UpdateResponseType update(
        @WebParam(name = "updateRequest", targetNamespace = "http://www.loc.gov/zing/srw/update/", partName = "updateRequest")
        UpdateRequestType updateRequest);

    /**
     * 
     * @param explainRequest
     * @return
     *     returns dk.dbc.oclc.wciru.ExplainResponseType
     */
    @WebMethod
    @WebResult(name = "explainResponse", targetNamespace = "http://www.loc.gov/zing/srw/update/", partName = "explainResponse")
    public ExplainResponseType explain(
        @WebParam(name = "explainRequest", targetNamespace = "http://www.loc.gov/zing/srw/update/", partName = "explainRequest")
        ExplainRequestType explainRequest);

}
