--
-- PostgreSQL database dump
--

-- Dumped from database version 9.5.4
-- Dumped by pg_dump version 9.5.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET client_min_messages = warning;
SET row_security = off;

SET search_path = public, pg_catalog;

--
-- Data for Name: flow_components; Type: TABLE DATA; Schema: public; Owner: ja7
--

INSERT INTO flow_components VALUES (2152, '{"name": "smaTest9", "description": "Test af oprettelse med \"next\"", "javascripts": [], "svnRevision": 87446, "requireCache": "", "invocationMethod": "begin", "invocationJavascriptName": "trunk/js/cql_xml_to_html.js", "svnProjectForInvocationJavascript": "datawell-convert"}', 2, '{"name": "smaTest9", "description": "Test af oprettelse med \"next\"", "javascripts": [], "svnRevision": 87446, "requireCache": "", "invocationMethod": "begin", "invocationJavascriptName": "trunk/js/cql_xml_to_html.js", "svnProjectForInvocationJavascript": "datawell-convert"}');
INSERT INTO flow_components VALUES (1001, '{"name": "flowK nr 1", "description": "første flowkomponent til flow mere flere flowkomponenter", "javascripts": [], "svnRevision": 82807, "requireCache": "", "invocationMethod": "flowComponentOne", "invocationJavascriptName": "trunk/flowcomponentOne.js", "svnProjectForInvocationJavascript": "dataio-js-test-projects"}', 5, '{"name": "flowK nr 1", "description": "første flowkomponent til flow mere flere flowkomponenter", "javascripts": [], "svnRevision": 87684, "requireCache": "", "invocationMethod": "flowComponentOne", "invocationJavascriptName": "trunk/flowcomponentOne.js", "svnProjectForInvocationJavascript": "dataio-js-test-projects"}');
INSERT INTO flow_components VALUES (801, '{"name": "HiveFejl", "description": "til fremprovokering af fejl i hive", "javascripts": [], "svnRevision": 79125, "requireCache": "", "invocationMethod": "createHiveErrorFromFbsRecord", "invocationJavascriptName": "trunk/js/marc_fbs.js", "svnProjectForInvocationJavascript": "datawell-convert"}', 2, NULL);
INSERT INTO flow_components VALUES (901, '{"name": "Steens Nye Flowkomponent", "javascripts": [], "svnRevision": 82608, "requireCache": "", "invocationMethod": "begin", "invocationJavascriptName": "trunk/js/cql_xml_to_html.js", "svnProjectForInvocationJavascript": "datawell-convert"}', 1, NULL);
INSERT INTO flow_components VALUES (2851, '{"name": "sma test", "description": "testing", "javascripts": [], "svnRevision": 91492, "requireCache": "", "invocationMethod": "begin", "invocationJavascriptName": "trunk/js/xml_datawell_3.0.js", "svnProjectForInvocationJavascript": "datawell-convert"}', 2, '{"name": "sma test", "description": "testing", "javascripts": [], "svnRevision": 91492, "requireCache": "", "invocationMethod": "begin", "invocationJavascriptName": "trunk/js/xml_datawell_3.0.js", "svnProjectForInvocationJavascript": "datawell-convert"}');
INSERT INTO flow_components VALUES (651, '{"name": "smaTest12", "description": "Dette er en ny fin beskrivelse", "javascripts": [], "svnRevision": 78955, "requireCache": "", "invocationMethod": "funA", "invocationJavascriptName": "trunk/integration-test/gui-selenium/src/test/test-projects/main/trunk/main.js", "svnProjectForInvocationJavascript": "dataio"}', 13, NULL);
INSERT INTO flow_components VALUES (4903, '{"name": "FBS_Edu_forbehandling", "description": "Flowkomponent som forbehandler en post til FBS Uddannelsessystemet", "javascripts": [], "svnRevision": 100233, "requireCache": "", "invocationMethod": "prepareFbsEducationRecordForRawRepo", "invocationJavascriptName": "trunk/js/marcx_io_raw_repo.js", "svnProjectForInvocationJavascript": "datawell-convert"}', 4, '{"name": "FBS_Edu_forbehandling", "description": "Flowkomponent som forbehandler en post til FBS Uddannelsessystemet", "javascripts": [], "svnRevision": 100233, "requireCache": "", "invocationMethod": "prepareFbsEducationRecordForRawRepo", "invocationJavascriptName": "trunk/js/marcx_io_raw_repo.js", "svnProjectForInvocationJavascript": "datawell-convert"}');
INSERT INTO flow_components VALUES (652, '{"name": "smaTest2", "description": "Description.", "javascripts": [], "svnRevision": 78580, "requireCache": "", "invocationMethod": "begin", "invocationJavascriptName": "trunk/js/xml_datawell_3.0.js", "svnProjectForInvocationJavascript": "datawell-convert"}', 2, NULL);
INSERT INTO flow_components VALUES (855, '{"name": "ØKP test", "description": "skal slettes", "javascripts": [], "svnRevision": 81689, "requireCache": "", "invocationMethod": "begin", "invocationJavascriptName": "trunk/js/cql_xml_to_html.js", "svnProjectForInvocationJavascript": "datawell-convert"}', 4, NULL);
INSERT INTO flow_components VALUES (854, '{"name": "FFU forbehandling", "description": "Forbehandling af poster fra FFU-bibliotekerne på vej til råpost repo", "javascripts": [], "svnRevision": 102019, "requireCache": "", "invocationMethod": "prepareResearchRecordForRawRepo", "invocationJavascriptName": "trunk/js/marcx_io_raw_repo.js", "svnProjectForInvocationJavascript": "datawell-convert"}', 64, '{"name": "FFU forbehandling", "description": "Forbehandling af poster fra FFU-bibliotekerne på vej til råpost repo", "javascripts": [], "svnRevision": 102019, "requireCache": "", "invocationMethod": "prepareResearchRecordForRawRepo", "invocationJavascriptName": "trunk/js/marcx_io_raw_repo.js", "svnProjectForInvocationJavascript": "datawell-convert"}');
INSERT INTO flow_components VALUES (102, '{"name": "Bibzoom Album", "description": "Konvertering af bibzoom album poster til brønd", "javascripts": [], "svnRevision": 77345, "requireCache": "", "invocationMethod": "createDatawellXmlFromBibzoomAlbums", "invocationJavascriptName": "trunk/js/xml_datawell_3.0.js", "svnProjectForInvocationJavascript": "datawell-convert"}', 4, NULL);
INSERT INTO flow_components VALUES (1002, '{"name": "flowK nr 2", "description": "anden flowkomponent til flow mere flere flowkomponenter", "javascripts": [], "svnRevision": 82808, "requireCache": "", "invocationMethod": "flowComponentTwo", "invocationJavascriptName": "trunk/flowcomponentTwo.js", "svnProjectForInvocationJavascript": "dataio-js-test-projects"}', 6, NULL);
INSERT INTO flow_components VALUES (7, '{"name": "RR2Brønd", "description": "Almindeligt brøndkonverteringsflow fra Råpost Repo til displaybrønden", "javascripts": [], "svnRevision": 101424, "requireCache": "", "invocationMethod": "convertRawRecord", "invocationJavascriptName": "trunk/js/marc_fbs.js", "svnProjectForInvocationJavascript": "datawell-convert"}', 50, '{"name": "RR2Brønd", "description": "Almindeligt brøndkonverteringsflow fra Råpost Repo til displaybrønden", "javascripts": [], "svnRevision": 101436, "requireCache": "", "invocationMethod": "convertRawRecord", "invocationJavascriptName": "trunk/js/marc_fbs.js", "svnProjectForInvocationJavascript": "datawell-convert"}');
INSERT INTO flow_components VALUES (1907, '{"name": "demo1", "description": "test komponent", "javascripts": [], "svnRevision": 87060, "requireCache": "", "invocationMethod": "jeg_kan_lige_saa_godt_sige_det_som_det_er", "invocationJavascriptName": "trunk/demo_script.js", "svnProjectForInvocationJavascript": "dataio-js-test-projects"}', 17, NULL);
INSERT INTO flow_components VALUES (753, '{"name": "RR2BrøndExttest - skal slettes", "description": "skal slettes", "javascripts": [], "svnRevision": 83662, "requireCache": "", "invocationMethod": "convertRawRecord", "invocationJavascriptName": "trunk/js/marc_fbs.js", "svnProjectForInvocationJavascript": "datawell-convert"}', 6, NULL);
INSERT INTO flow_components VALUES (701, '{"name": "rtrt", "description": "skal slettes", "javascripts": [], "svnRevision": 78828, "requireCache": "", "invocationMethod": "createDatawellXmlFromTS1001", "invocationJavascriptName": "trunk/js/xml_datawell_3.0.js", "svnProjectForInvocationJavascript": "datawell-convert"}', 6, NULL);
INSERT INTO flow_components VALUES (2, '{"name": "RR2FBS", "description": "Poster der skal til FBS Webservice - næsten uændret - vi fjerner DBCs bogstavfelter", "javascripts": [], "svnRevision": 96972, "requireCache": "", "invocationMethod": "transportRecord", "invocationJavascriptName": "trunk/js/marc_fbs.js", "svnProjectForInvocationJavascript": "datawell-convert"}', 20, '{"name": "RR2FBS", "description": "Poster der skal til FBS Webservice - næsten uændret - vi fjerner DBCs bogstavfelter", "javascripts": [], "svnRevision": 96972, "requireCache": "", "invocationMethod": "transportRecord", "invocationJavascriptName": "trunk/js/marc_fbs.js", "svnProjectForInvocationJavascript": "datawell-convert"}');
INSERT INTO flow_components VALUES (653, '{"name": "smaTest3", "description": "Bør slettes....", "javascripts": [], "svnRevision": 78665, "requireCache": "", "invocationMethod": "begin", "invocationJavascriptName": "trunk/js/cql_xml_to_html.js", "svnProjectForInvocationJavascript": "datawell-convert"}', 12, '{"name": "smaTest3", "description": "Bør slettes....", "javascripts": [], "svnRevision": 87433, "requireCache": "", "invocationMethod": "begin", "invocationJavascriptName": "trunk/js/cql_xml_to_html.js", "svnProjectForInvocationJavascript": "datawell-convert"}');
INSERT INTO flow_components VALUES (853, '{"name": "ZKP test", "description": "skal slettes", "javascripts": [], "svnRevision": 81689, "requireCache": "", "invocationMethod": "begin", "invocationJavascriptName": "trunk/js/cql_xml_to_html.js", "svnProjectForInvocationJavascript": "datawell-convert"}', 4, NULL);
INSERT INTO flow_components VALUES (52, '{"name": "tracer-bullet-component", "description": "Minimalt script til basal system test", "javascripts": [], "svnRevision": 1, "requireCache": "", "invocationMethod": "invocationFunction", "invocationJavascriptName": "tracer-bullet-javascript", "svnProjectForInvocationJavascript": "svnprojectforinvocationjavascript"}', 1, NULL);
INSERT INTO flow_components VALUES (852, '{"name": "AKP test", "description": "skal slettes", "javascripts": [], "svnRevision": 81689, "requireCache": "", "invocationMethod": "begin", "invocationJavascriptName": "trunk/js/cql_xml_to_html.js", "svnProjectForInvocationJavascript": "datawell-convert"}', 7, '{"name": "AKP test", "description": "skal slettes", "javascripts": [], "svnRevision": 88286, "requireCache": "", "invocationMethod": "begin", "invocationJavascriptName": "trunk/js/cql_xml_to_html.js", "svnProjectForInvocationJavascript": "datawell-convert"}');
INSERT INTO flow_components VALUES (2062, '{"name": "smaTest6", "description": "Jeg ønsker mig en slet knap...", "javascripts": [], "svnRevision": 87339, "requireCache": "", "invocationMethod": "invocationFunction", "invocationJavascriptName": "trunk/performance-test/src/test/resources/jda.js", "svnProjectForInvocationJavascript": "dataio"}', 1, NULL);
INSERT INTO flow_components VALUES (2051, '{"name": "sma", "description": "test more because javaScriptProjectFetcher is sloooow", "javascripts": [], "svnRevision": 87332, "requireCache": "", "invocationMethod": "invocationFunction", "invocationJavascriptName": "trunk/performance-test/src/test/resources/jda.js", "svnProjectForInvocationJavascript": "dataio"}', 6, '{"name": "sma", "description": "test more because javaScriptProjectFetcher is sloooow", "javascripts": [], "svnRevision": 87520, "requireCache": "", "invocationMethod": "invocationFunction", "invocationJavascriptName": "trunk/performance-test/src/test/resources/jda.js", "svnProjectForInvocationJavascript": "dataio"}');
INSERT INTO flow_components VALUES (2255, '{"name": "smaTest1", "description": "Test af markering af nyoprettet flow komponent i oversigten.", "javascripts": [], "svnRevision": 87519, "requireCache": "", "invocationMethod": "begin", "invocationJavascriptName": "trunk/js/cql_xml_to_html.js", "svnProjectForInvocationJavascript": "datawell-convert"}', 2, '{"name": "smaTest1", "description": "Test af markering af nyoprettet flow komponent i oversigten.", "javascripts": [], "svnRevision": 87519, "requireCache": "", "invocationMethod": "begin", "invocationJavascriptName": "trunk/js/cql_xml_to_html.js", "svnProjectForInvocationJavascript": "datawell-convert"}');
INSERT INTO flow_components VALUES (1901, '{"name": "E4X-brønd", "description": "Brøndkonvertering stadig med E4X", "javascripts": [], "svnRevision": 83776, "requireCache": "", "invocationMethod": "convertRawRecord", "invocationJavascriptName": "trunk/js/marc_fbs.js", "svnProjectForInvocationJavascript": "datawell-convert"}', 12, '{"name": "E4X-brønd", "description": "Brøndkonvertering stadig med E4X", "javascripts": [], "svnRevision": 88247, "requireCache": "", "invocationMethod": "convertRawRecord", "invocationJavascriptName": "trunk/js/marc_fbs.js", "svnProjectForInvocationJavascript": "datawell-convert"}');
INSERT INTO flow_components VALUES (1951, '{"name": "kbp demo", "description": "demo skal settes", "javascripts": [], "svnRevision": 87060, "requireCache": "", "invocationMethod": "jeg_kan_lige_saa_godt_sige_det_som_det_er", "invocationJavascriptName": "trunk/demo_script.js", "svnProjectForInvocationJavascript": "dataio-js-test-projects"}', 1, NULL);
INSERT INTO flow_components VALUES (851, '{"name": "ÅKP test", "description": "skal slettes.", "javascripts": [], "svnRevision": 81689, "requireCache": "", "invocationMethod": "begin", "invocationJavascriptName": "trunk/js/cql_xml_to_html.js", "svnProjectForInvocationJavascript": "datawell-convert"}', 3, NULL);
INSERT INTO flow_components VALUES (2859, '{"name": "sma special test", "description": "test test", "javascripts": [], "svnRevision": 91492, "requireCache": "", "invocationMethod": "begin", "invocationJavascriptName": "trunk/js/xml_datawell_3.0.js", "svnProjectForInvocationJavascript": "datawell-convert"}', 2, '{"name": "sma special test", "description": "test test", "javascripts": [], "svnRevision": 91492, "requireCache": "", "invocationMethod": "begin", "invocationJavascriptName": "trunk/js/xml_datawell_3.0.js", "svnProjectForInvocationJavascript": "datawell-convert"}');
INSERT INTO flow_components VALUES (2054, '{"name": "smaTest4", "description": "test noget mere", "javascripts": [], "svnRevision": 87332, "requireCache": "", "invocationMethod": "invocationFunction", "invocationJavascriptName": "trunk/performance-test/src/test/resources/jda.js", "svnProjectForInvocationJavascript": "dataio"}', 2, NULL);
INSERT INTO flow_components VALUES (2052, '{"name": "smaTest", "description": "Skal slettes", "javascripts": [], "svnRevision": 87332, "requireCache": "", "invocationMethod": "invocationFunction", "invocationJavascriptName": "trunk/performance-test/src/test/resources/jda.js", "svnProjectForInvocationJavascript": "dataio"}', 2, NULL);
INSERT INTO flow_components VALUES (1201, '{"name": "require-tracebullet", "description": "tracebullet der bruge require", "javascripts": [], "svnRevision": 83597, "requireCache": "", "invocationMethod": "tracerbullet_xmldom", "invocationJavascriptName": "trunk/tracerBulletXmlDom.js", "svnProjectForInvocationJavascript": "dataio-js-test-projects"}', 7, '{"name": "require-tracebullet", "description": "tracebullet der bruge require", "javascripts": [], "svnRevision": 93542, "requireCache": "", "invocationMethod": "tracerbullet_xmldom", "invocationJavascriptName": "trunk/tracerBulletXmlDom.js", "svnProjectForInvocationJavascript": "dataio-js-test-projects"}');
INSERT INTO flow_components VALUES (2061, '{"name": "smaTest5", "description": "testing", "javascripts": [], "svnRevision": 87339, "requireCache": "", "invocationMethod": "invocationFunction", "invocationJavascriptName": "trunk/performance-test/src/test/resources/jda.js", "svnProjectForInvocationJavascript": "dataio"}', 1, NULL);
INSERT INTO flow_components VALUES (4053, '{"name": "nashorn test", "description": "nashorn performance test", "javascripts": [], "svnRevision": 97750, "requireCache": "", "invocationMethod": "main", "invocationJavascriptName": "trunk/nashorn_test.js", "svnProjectForInvocationJavascript": "dataio-js-test-projects"}', 2, '{"name": "nashorn test", "description": "nashorn performance test", "javascripts": [], "svnRevision": 97750, "requireCache": "", "invocationMethod": "main", "invocationJavascriptName": "trunk/nashorn_test.js", "svnProjectForInvocationJavascript": "dataio-js-test-projects"}');
INSERT INTO flow_components VALUES (3402, '{"name": "SLET MIG", "description": "SLET DENNE!", "javascripts": [], "svnRevision": 94625, "requireCache": "", "invocationMethod": "invocationFunction", "invocationJavascriptName": "trunk/performance-test/src/test/resources/jda.js", "svnProjectForInvocationJavascript": "dataio"}', 4, '{"name": "SLET MIG", "description": "SLET DENNE!", "javascripts": [], "svnRevision": 94625, "requireCache": "", "invocationMethod": "invocationFunction", "invocationJavascriptName": "trunk/performance-test/src/test/resources/jda.js", "svnProjectForInvocationJavascript": "dataio"}');
INSERT INTO flow_components VALUES (4056, '{"name": "nashorn single script test", "description": "nashorn uden brug af dbc modul system", "javascripts": [], "svnRevision": 97757, "requireCache": "", "invocationMethod": "main", "invocationJavascriptName": "trunk/nashorn_single_script_test.js", "svnProjectForInvocationJavascript": "dataio-js-test-projects"}', 2, '{"name": "nashorn single script test", "description": "nashorn uden brug af dbc modul system", "javascripts": [], "svnRevision": 97757, "requireCache": "", "invocationMethod": "main", "invocationJavascriptName": "trunk/nashorn_single_script_test.js", "svnProjectForInvocationJavascript": "dataio-js-test-projects"}');
INSERT INTO flow_components VALUES (1451, '{"name": "specialTegnstest_2-3 4", "description": "skal slettes", "javascripts": [], "svnRevision": 84603, "requireCache": "", "invocationMethod": "begin", "invocationJavascriptName": "trunk/js/cql_xml_to_html.js", "svnProjectForInvocationJavascript": "datawell-convert"}', 3, NULL);
INSERT INTO flow_components VALUES (1601, '{"name": "RR2basis", "description": "almindeligt flow fra Råpost Repo til basis - posten kører uændret igennem men der sættes flag for at posten skal konverteres til iso2709 i sinken", "javascripts": [], "svnRevision": 96972, "requireCache": "", "invocationMethod": "convertRawRecordToBasis", "invocationJavascriptName": "trunk/js/marc_basis.js", "svnProjectForInvocationJavascript": "datawell-convert"}', 6, '{"name": "RR2basis", "description": "almindeligt flow fra Råpost Repo til basis - posten kører uændret igennem men der sættes flag for at posten skal konverteres til iso2709 i sinken", "javascripts": [], "svnRevision": 96972, "requireCache": "", "invocationMethod": "convertRawRecordToBasis", "invocationJavascriptName": "trunk/js/marc_basis.js", "svnProjectForInvocationJavascript": "datawell-convert"}');
INSERT INTO flow_components VALUES (2063, '{"name": "smaTest7", "description": "Skal slettes", "javascripts": [], "svnRevision": 87278, "requireCache": "", "invocationMethod": "begin", "invocationJavascriptName": "trunk/js/cql_xml_to_html.js", "svnProjectForInvocationJavascript": "datawell-convert"}', 10, '{"name": "smaTest7", "description": "Skal slettes", "javascripts": [], "svnRevision": 87392, "requireCache": "", "invocationMethod": "begin", "invocationJavascriptName": "trunk/js/cql_xml_to_html.js", "svnProjectForInvocationJavascript": "datawell-convert"}');
INSERT INTO flow_components VALUES (2351, '{"name": "diff-test", "description": "Simpelt sandkasse projekt benyttet i forbindelse med afprøvning af diff funktionalitet.", "javascripts": [], "svnRevision": 87987, "requireCache": "", "invocationMethod": "convert", "invocationJavascriptName": "trunk/js/converter.js", "svnProjectForInvocationJavascript": "dataio-diff-test"}', 7, '{"name": "diff-test", "description": "Simpelt sandkasse projekt benyttet i forbindelse med afprøvning af diff funktionalitet.", "javascripts": [], "svnRevision": 88145, "requireCache": "", "invocationMethod": "convert", "invocationJavascriptName": "trunk/js/converter.js", "svnProjectForInvocationJavascript": "dataio-diff-test"}');
INSERT INTO flow_components VALUES (1751, '{"name": "TestCreateWithDescription", "description": "Testing description field.", "javascripts": [], "svnRevision": 86242, "requireCache": "", "invocationMethod": "invocationFunction", "invocationJavascriptName": "trunk/performance-test/src/test/resources/jda.js", "svnProjectForInvocationJavascript": "dataio"}', 1, NULL);
INSERT INTO flow_components VALUES (1902, '{"name": "XMLDOM-brønd", "description": "Brøndkonvertering nu med XMLDOM og ikke længere E4X. ", "javascripts": [], "svnRevision": 87727, "requireCache": "", "invocationMethod": "convertRawRecord", "invocationJavascriptName": "trunk/js/marc_fbs.js", "svnProjectForInvocationJavascript": "datawell-convert"}', 13, '{"name": "XMLDOM-brønd", "description": "Brøndkonvertering nu med XMLDOM og ikke længere E4X. ", "javascripts": [], "svnRevision": 88823, "requireCache": "", "invocationMethod": "convertRawRecord", "invocationJavascriptName": "trunk/js/marc_fbs.js", "svnProjectForInvocationJavascript": "datawell-convert"}');
INSERT INTO flow_components VALUES (2064, '{"name": "smaTest8", "description": "Test af update med \"Next\"", "javascripts": [], "svnRevision": 87278, "requireCache": "", "invocationMethod": "begin", "invocationJavascriptName": "trunk/js/cql_xml_to_html.js", "svnProjectForInvocationJavascript": "datawell-convert"}', 26, '{"name": "smaTest8", "description": "Test af update med \"Next\"", "javascripts": [], "svnRevision": 87390, "requireCache": "", "invocationMethod": "begin", "invocationJavascriptName": "trunk/js/cql_xml_to_html.js", "svnProjectForInvocationJavascript": "datawell-convert"}');


--
-- Data for Name: flows; Type: TABLE DATA; Schema: public; Owner: ja7
--

INSERT INTO flows VALUES (2352, '{"name": "diff-test", "components": [{"id": 2351, "next": {"name": "diff-test", "description": "Simpelt sandkasse projekt benyttet i forbindelse med afprøvning af diff funktionalitet.", "javascripts": [], "svnRevision": 88145, "requireCache": "", "invocationMethod": "convert", "invocationJavascriptName": "trunk/js/converter.js", "svnProjectForInvocationJavascript": "dataio-diff-test"}, "content": {"name": "diff-test", "description": "Simpelt sandkasse projekt benyttet i forbindelse med afprøvning af diff funktionalitet.", "javascripts": [], "svnRevision": 87987, "requireCache": "", "invocationMethod": "convert", "invocationJavascriptName": "trunk/js/converter.js", "svnProjectForInvocationJavascript": "dataio-diff-test"}, "version": 7}], "description": "Simpelt test flow benyttet i forbindelse med afprøvning af diff funktionalitet."}', 5);
INSERT INTO flows VALUES (53, '{"name": "tracer-bullet-flow", "components": [{"id": 52, "next": null, "content": {"name": "tracer-bullet-component", "description": "Minimalt script til basal system test", "javascripts": [], "svnRevision": 1, "requireCache": "", "invocationMethod": "invocationFunction", "invocationJavascriptName": "tracer-bullet-javascript", "svnProjectForInvocationJavascript": "svnprojectforinvocationjavascript"}, "version": 1}], "description": "description"}', 2);
INSERT INTO flows VALUES (1003, '{"name": "Flere flowkomponenter", "components": [{"id": 1001, "next": {"name": "flowK nr 1", "description": "første flowkomponent til flow mere flere flowkomponenter", "javascripts": [], "svnRevision": 87684, "requireCache": "", "invocationMethod": "flowComponentOne", "invocationJavascriptName": "trunk/flowcomponentOne.js", "svnProjectForInvocationJavascript": "dataio-js-test-projects"}, "content": {"name": "flowK nr 1", "description": "første flowkomponent til flow mere flere flowkomponenter", "javascripts": [], "svnRevision": 82807, "requireCache": "", "invocationMethod": "flowComponentOne", "invocationJavascriptName": "trunk/flowcomponentOne.js", "svnProjectForInvocationJavascript": "dataio-js-test-projects"}, "version": 5}, {"id": 1002, "next": null, "content": {"name": "flowK nr 2", "description": "anden flowkomponent til flow mere flere flowkomponenter", "javascripts": [], "svnRevision": 82808, "requireCache": "", "invocationMethod": "flowComponentTwo", "invocationJavascriptName": "trunk/flowcomponentTwo.js", "svnProjectForInvocationJavascript": "dataio-js-test-projects"}, "version": 6}], "description": "Vi tester om vi kan lave et flow med flere flowkomponenter"}', 22);
INSERT INTO flows VALUES (1602, '{"name": "RR2basis", "components": [{"id": 1601, "next": {"name": "RR2basis", "description": "almindeligt flow fra Råpost Repo til basis - posten kører uændret igennem men der sættes flag for at posten skal konverteres til iso2709 i sinken", "javascripts": [], "svnRevision": 96972, "requireCache": "", "invocationMethod": "convertRawRecordToBasis", "invocationJavascriptName": "trunk/js/marc_basis.js", "svnProjectForInvocationJavascript": "datawell-convert"}, "content": {"name": "RR2basis", "description": "almindeligt flow fra Råpost Repo til basis - posten kører uændret igennem men der sættes flag for at posten skal konverteres til iso2709 i sinken", "javascripts": [], "svnRevision": 96972, "requireCache": "", "invocationMethod": "convertRawRecordToBasis", "invocationJavascriptName": "trunk/js/marc_basis.js", "svnProjectForInvocationJavascript": "datawell-convert"}, "version": 6}], "description": "flow der kun pakker en post fra RR i addi-format, så den kan overleveres til en ES-basis-sink og videre derfra til Basis"}', 3);
INSERT INTO flows VALUES (3151, '{"name": "FFU2RR", "components": [{"id": 854, "next": {"name": "FFU forbehandling", "description": "Forbehandling af poster fra FFU-bibliotekerne på vej til råpost repo", "javascripts": [], "svnRevision": 102019, "requireCache": "", "invocationMethod": "prepareResearchRecordForRawRepo", "invocationJavascriptName": "trunk/js/marcx_io_raw_repo.js", "svnProjectForInvocationJavascript": "datawell-convert"}, "content": {"name": "FFU forbehandling", "description": "Forbehandling af poster fra FFU-bibliotekerne på vej til råpost repo", "javascripts": [], "svnRevision": 102019, "requireCache": "", "invocationMethod": "prepareResearchRecordForRawRepo", "invocationJavascriptName": "trunk/js/marcx_io_raw_repo.js", "svnProjectForInvocationJavascript": "datawell-convert"}, "version": 64}], "description": "Forbehandling af FFU-poster på vej til Råpost Repo"}', 23);
INSERT INTO flows VALUES (9, '{"name": "RR2Brønd", "components": [{"id": 7, "next": {"name": "RR2Brønd", "description": "Almindeligt brøndkonverteringsflow fra Råpost Repo til displaybrønden", "javascripts": [], "svnRevision": 101436, "requireCache": "", "invocationMethod": "convertRawRecord", "invocationJavascriptName": "trunk/js/marc_fbs.js", "svnProjectForInvocationJavascript": "datawell-convert"}, "content": {"name": "RR2Brønd", "description": "Almindeligt brøndkonverteringsflow fra Råpost Repo til displaybrønden", "javascripts": [], "svnRevision": 101424, "requireCache": "", "invocationMethod": "convertRawRecord", "invocationJavascriptName": "trunk/js/marc_fbs.js", "svnProjectForInvocationJavascript": "datawell-convert"}, "version": 50}], "description": "Jacascriptbehandling af poster fra RR til Brønd 3.5"}', 30);
INSERT INTO flows VALUES (4054, '{"name": "nashorn test", "components": [{"id": 4053, "next": {"name": "nashorn test", "description": "nashorn performance test", "javascripts": [], "svnRevision": 97750, "requireCache": "", "invocationMethod": "main", "invocationJavascriptName": "trunk/nashorn_test.js", "svnProjectForInvocationJavascript": "dataio-js-test-projects"}, "content": {"name": "nashorn test", "description": "nashorn performance test", "javascripts": [], "svnRevision": 97750, "requireCache": "", "invocationMethod": "main", "invocationJavascriptName": "trunk/nashorn_test.js", "svnProjectForInvocationJavascript": "dataio-js-test-projects"}, "version": 2}], "description": "nashorn performance test"}', 1);
INSERT INTO flows VALUES (4057, '{"name": "nashorn single script test", "components": [{"id": 4056, "next": {"name": "nashorn single script test", "description": "nashorn uden brug af dbc modul system", "javascripts": [], "svnRevision": 97757, "requireCache": "", "invocationMethod": "main", "invocationJavascriptName": "trunk/nashorn_single_script_test.js", "svnProjectForInvocationJavascript": "dataio-js-test-projects"}, "content": {"name": "nashorn single script test", "description": "nashorn uden brug af dbc modul system", "javascripts": [], "svnRevision": 97757, "requireCache": "", "invocationMethod": "main", "invocationJavascriptName": "trunk/nashorn_single_script_test.js", "svnProjectForInvocationJavascript": "dataio-js-test-projects"}, "version": 2}], "description": "nashorn uden brug af dbc modul system"}', 1);


--
-- PostgreSQL database dump complete
--

