insert into harvester_configs (id, version , type, content ) values ( 1, 1, 'dk.dbc.dataio.harvester.types.RRHarvesterConfig', '{"content": {"includeRelations": true, "resource": "jdbc/dataio/rawrepo", "format": "katalog", "batchSize": 10000, "destination": "testbroend-i01", "consumerId": "broend-sync", "isEnabled": false, "openAgencyTarget": {"url": "http://openagency.addi.dk/2.25/"}, "formatOverrides": {"870970": "basis"}, "type": "TEST", "id": "broend-sync"}, "version": 1, "type": "dk.dbc.dataio.harvester.types.RRHarvesterConfig", "id": 1}'::jsonb);
insert into harvester_configs (id, version , type, content ) values ( 2, 1, 'dk.dbc.dataio.harvester.types.RRHarvesterConfig', '{"content": {"includeRelations": true, "resource": "jdbc/dataio/rawrepo-loadtest", "format": "katalog", "batchSize": 10000, "destination": "broend3-loadtest", "consumerId": "broend-sync", "isEnabled": false, "openAgencyTarget": {"url": "http://openagency.addi.dk/2.25/"}, "formatOverrides": {"870970": "basis"}, "type": "TEST", "id": "broend-sync-loadtest"}, "version": 1, "type": "dk.dbc.dataio.harvester.types.RRHarvesterConfig", "id": 2}'::jsonb);
insert into harvester_configs (id, version , type, content ) values ( 3, 1, 'dk.dbc.dataio.harvester.types.RRHarvesterConfig', '{"content": {"includeRelations": true, "resource": "jdbc/dataio/rawrepo", "format": "basis", "batchSize": 10000, "destination": "testbasis-i01", "consumerId": "basis-decentral", "isEnabled": true, "openAgencyTarget": {"url": "http://openagency.addi.dk/2.25/"}, "formatOverrides": {"870970": "basis"}, "type": "TEST", "id": "basis-decentral"}, "version": 1, "type": "dk.dbc.dataio.harvester.types.RRHarvesterConfig", "id": 3}'::jsonb);
insert into harvester_configs (id, version , type, content ) values ( 4, 1, 'dk.dbc.dataio.harvester.types.RRHarvesterConfig', '{"content": {"includeRelations": true, "resource": "jdbc/dataio/rawrepo-boblebad", "format": "basis", "batchSize": 10000, "destination": "testbasis-boblebad", "consumerId": "basis-decentral", "isEnabled": true, "openAgencyTarget": {"url": "http://openagency.addi.dk/2.25/"}, "formatOverrides": {"870970": "basis"}, "type": "TEST", "id": "testbasis-sync-boble"}, "version": 1, "type": "dk.dbc.dataio.harvester.types.RRHarvesterConfig", "id": 4}'::jsonb);
insert into harvester_configs (id, version , type, content ) values ( 5, 1, 'dk.dbc.dataio.harvester.types.RRHarvesterConfig', '{"content": {"includeRelations": true, "resource": "jdbc/dataio/rawrepo-boblebad", "format": "katalog", "batchSize": 10000, "destination": "broend-boblebad", "consumerId": "broend-sync", "isEnabled": true, "openAgencyTarget": {"url": "http://openagency.addi.dk/2.25/"}, "formatOverrides": {"870970": "basis"}, "id": "broend-sync-boble"}, "version": 1, "type": "dk.dbc.dataio.harvester.types.RRHarvesterConfig", "id": 5}'::jsonb);
insert into harvester_configs (id, version , type, content ) values ( 6, 1, 'dk.dbc.dataio.harvester.types.RRHarvesterConfig', '{"content": {"includeRelations": true, "resource": "jdbc/dataio/rawrepo-boblebad", "format": "katalog", "batchSize": 10000, "destination": "broend-boblebad-prio1", "consumerId": "broend-sync-prio1", "isEnabled": true, "openAgencyTarget": {"url": "http://openagency.addi.dk/2.25/"}, "formatOverrides": {"870970": "basis"}, "id": "broend-sync-boble-prio1"}, "version": 1, "type": "dk.dbc.dataio.harvester.types.RRHarvesterConfig", "id": 6}'::jsonb);
insert into harvester_configs (id, version , type, content ) values ( 7, 1, 'dk.dbc.dataio.harvester.types.RRHarvesterConfig', '{"content": {"includeRelations": false, "resource": "jdbc/dataio/rawrepo", "format": "katalog", "batchSize": 10000, "destination": "fbs-i01", "consumerId": "fbs-sync", "isEnabled": true, "openAgencyTarget": {"url": "http://openagency.addi.dk/2.25/"}, "formatOverrides": {}, "type": "TEST", "id": "fbs-sync"}, "version": 1, "type": "dk.dbc.dataio.harvester.types.RRHarvesterConfig", "id": 7}'::jsonb);
insert into harvester_configs (id, version , type, content ) values ( 8, 1, 'dk.dbc.dataio.harvester.types.RRHarvesterConfig', '{"content": {"includeRelations": false, "resource": "jdbc/dataio/rawrepo-boblebad", "format": "katalog", "batchSize": 10000, "destination": "cicero-boblebad", "consumerId": "fbs-sync", "isEnabled": true, "openAgencyTarget": {"url": "http://openagency.addi.dk/2.25/"}, "formatOverrides": {}, "id": "cicero-sync"}, "version": 1, "type": "dk.dbc.dataio.harvester.types.RRHarvesterConfig", "id": 8}'::jsonb);
insert into harvester_configs (id, version , type, content ) values ( 9, 1, 'dk.dbc.dataio.harvester.types.RRHarvesterConfig', '{"content": {"includeRelations": true, "resource": "jdbc/dataio/rawrepo-cisterne", "format": "katalog", "batchSize": 10000, "destination": "broend-cisterne", "consumerId": "broend-sync", "isEnabled": true, "openAgencyTarget": {"url": "http://openagency.addi.dk/2.25/"}, "formatOverrides": {"870970": "basis"}, "id": "broend-sync-cisterne"}, "version": 1, "type": "dk.dbc.dataio.harvester.types.RRHarvesterConfig", "id": 9}'::jsonb);
insert into harvester_configs (id, version , type, content ) values ( 10, 1, 'dk.dbc.dataio.harvester.types.RRHarvesterConfig', '{"content": {"includeRelations": false, "resource": "jdbc/dataio/rawrepo-cisterne", "format": "katalog", "batchSize": 10000, "destination": "cicero-cisterne", "consumerId": "broend-sync-forkert", "isEnabled": true, "openAgencyTarget": {"url": "http://openagency.addi.dk/2.25/"}, "formatOverrides": {}, "id": "fbs-sync-cisterne"}, "version": 1, "type": "dk.dbc.dataio.harvester.types.RRHarvesterConfig", "id": 10}'::jsonb);
insert into harvester_configs (id, version , type, content ) values ( 11, 1, 'dk.dbc.dataio.harvester.types.RRHarvesterConfig', '{"content": {"includeRelations": true, "resource": "jdbc/dataio/rawrepo-cisterne", "format": "basis", "batchSize": 10000, "destination": "basis-cisterne", "consumerId": "basis-decentral", "isEnabled": true, "openAgencyTarget": {"url": "http://openagency.addi.dk/2.25/"}, "formatOverrides": {"870970": "basis"}, "id": "basis-sync-cisterne"}, "version": 1, "type": "dk.dbc.dataio.harvester.types.RRHarvesterConfig", "id": 11}'::jsonb);
insert into harvester_configs (id, version , type, content ) values ( 12, 1, 'dk.dbc.dataio.harvester.types.RRHarvesterConfig', '{"content": {"includeRelations": true, "resource": "jdbc/dataio/rawrepo", "format": "katalog", "batchSize": 10000, "destination": "broend30", "consumerId": "broend30-sync", "isEnabled": true, "openAgencyTarget": {"url": "http://openagency.addi.dk/2.25/"}, "formatOverrides": {}, "type": "TEST", "id": "fbs-test-sync-broend30"}, "version": 1, "type": "dk.dbc.dataio.harvester.types.RRHarvesterConfig", "id": 12}'::jsonb);
insert into harvester_configs (id, version , type, content ) values ( 13, 1, 'dk.dbc.dataio.harvester.types.RRHarvesterConfig', '{"content": {"includeRelations": true, "resource": "jdbc/dataio/rawrepo-cisterne", "format": "katalog", "batchSize": 10000, "destination": "broend-aqua", "consumerId": "broend30-sync", "isEnabled": true, "openAgencyTarget": {"url": "http://openagency.addi.dk/2.25/"}, "formatOverrides": {"870970": "basis"}, "type": "TRANSIENT", "id": "broend30-sync-cisterne"}, "version": 1, "type": "dk.dbc.dataio.harvester.types.RRHarvesterConfig", "id": 13}'::jsonb);

insert into harvester_configs (id, version , type, content ) values ( 14, 1, 'dk.dbc.dataio.harvester.types.OLDRRHarvesterConfig', '{"content": {"includeRelations": true, "resource": "jdbc/dataio/rawrepo-cisterne", "format": "katalog", "batchSize": 10000, "destination": "broend-aqua", "consumerId": "broend30-sync", "isEnabled": true, "openAgencyTarget": {"url": "http://openagency.addi.dk/2.25/"}, "formatOverrides": {"870970": "basis"}, "type": "TRANSIENT", "id": "broend30-sync-cisterne"}, "version": 1, "type": "dk.dbc.dataio.harvester.types.RRHarvesterConfig", "id": 13}'::jsonb);
