insert into harvester_configs (id, version , type, content ) values ( 1, 1, 'dk.dbc.dataio.harvester.types.RRHarvesterConfig', '{"includeRelations": true, "resource": "jdbc/dataio/rawrepo", "format": "katalog", "batchSize": 10000, "destination": "testbroend-i01", "consumerId": "broend-sync", "enabled": false, "openAgencyTarget": {"url": "http://openagency.addi.dk/2.25/"}, "formatOverrides": {"870970": "basis"}, "type": "TEST", "id": "broend-sync"}'::jsonb);
insert into harvester_configs (id, version , type, content ) values ( 2, 1, 'dk.dbc.dataio.harvester.types.RRHarvesterConfig', '{"includeRelations": true, "resource": "jdbc/dataio/rawrepo-loadtest", "format": "katalog", "batchSize": 10000, "destination": "broend3-loadtest", "consumerId": "broend-sync", "enabled": false, "openAgencyTarget": {"url": "http://openagency.addi.dk/2.25/"}, "formatOverrides": {"870970": "basis"}, "type": "TEST", "id": "broend-sync-loadtest"}'::jsonb);
insert into harvester_configs (id, version , type, content ) values ( 3, 1, 'dk.dbc.dataio.harvester.types.RRHarvesterConfig', '{"includeRelations": true, "resource": "jdbc/dataio/rawrepo", "format": "basis", "batchSize": 10000, "destination": "testbasis-i01", "consumerId": "basis-decentral", "enabled": true, "openAgencyTarget": {"url": "http://openagency.addi.dk/2.25/"}, "formatOverrides": {"870970": "basis"}, "type": "TEST", "id": "basis-decentral"}');
insert into harvester_configs (id, version , type, content ) values ( 4, 1, 'dk.dbc.dataio.harvester.types.RRHarvesterConfig', '{"includeRelations": true, "resource": "jdbc/dataio/rawrepo-boblebad", "format": "basis", "batchSize": 10000, "destination": "testbasis-boblebad", "consumerId": "basis-decentral", "enabled": true, "openAgencyTarget": {"url": "http://openagency.addi.dk/2.25/"}, "formatOverrides": {"870970": "basis"}, "type": "TEST", "id": "testbasis-sync-boble"}'::jsonb);
insert into harvester_configs (id, version , type, content ) values ( 5, 1, 'dk.dbc.dataio.harvester.types.RRHarvesterConfig', '{"includeRelations": true, "resource": "jdbc/dataio/rawrepo-boblebad", "format": "katalog", "batchSize": 10000, "destination": "broend-boblebad", "consumerId": "broend-sync", "enabled": true, "openAgencyTarget": {"url": "http://openagency.addi.dk/2.25/"}, "formatOverrides": {"870970": "basis"}, "id": "broend-sync-boble"}'::jsonb);
insert into harvester_configs (id, version , type, content ) values ( 6, 1, 'dk.dbc.dataio.harvester.types.RRHarvesterConfig', '{"includeRelations": true, "resource": "jdbc/dataio/rawrepo-boblebad", "format": "katalog", "batchSize": 10000, "destination": "broend-boblebad-prio1", "consumerId": "broend-sync-prio1", "enabled": true, "openAgencyTarget": {"url": "http://openagency.addi.dk/2.25/"}, "formatOverrides": {"870970": "basis"}, "id": "broend-sync-boble-prio1"}'::jsonb);
insert into harvester_configs (id, version , type, content ) values ( 7, 1, 'dk.dbc.dataio.harvester.types.RRHarvesterConfig', '{"includeRelations": false, "resource": "jdbc/dataio/rawrepo", "format": "katalog", "batchSize": 10000, "destination": "fbs-i01", "consumerId": "fbs-sync", "enabled": true, "openAgencyTarget": {"url": "http://openagency.addi.dk/2.25/"}, "formatOverrides": {}, "type": "TEST", "id": "fbs-sync"}'::jsonb);
insert into harvester_configs (id, version , type, content ) values ( 8, 1, 'dk.dbc.dataio.harvester.types.RRHarvesterConfig', '{"includeRelations": false, "resource": "jdbc/dataio/rawrepo-boblebad", "format": "katalog", "batchSize": 10000, "destination": "cicero-boblebad", "consumerId": "fbs-sync", "enabled": true, "openAgencyTarget": {"url": "http://openagency.addi.dk/2.25/"}, "formatOverrides": {}, "id": "cicero-sync"}'::jsonb);
insert into harvester_configs (id, version , type, content ) values ( 9, 1, 'dk.dbc.dataio.harvester.types.RRHarvesterConfig', '{"includeRelations": true, "resource": "jdbc/dataio/rawrepo-cisterne", "format": "katalog", "batchSize": 10000, "destination": "broend-cisterne", "consumerId": "broend-sync", "enabled": true, "openAgencyTarget": {"url": "http://openagency.addi.dk/2.25/"}, "formatOverrides": {"870970": "basis"}, "id": "broend-sync-cisterne"}'::jsonb);
insert into harvester_configs (id, version , type, content ) values ( 10, 1, 'dk.dbc.dataio.harvester.types.RRHarvesterConfig', '{"includeRelations": false, "resource": "jdbc/dataio/rawrepo-cisterne", "format": "katalog", "batchSize": 10000, "destination": "cicero-cisterne", "consumerId": "broend-sync-forkert", "enabled": true, "openAgencyTarget": {"url": "http://openagency.addi.dk/2.25/"}, "formatOverrides": {}, "id": "fbs-sync-cisterne"}'::jsonb);
insert into harvester_configs (id, version , type, content ) values ( 11, 1, 'dk.dbc.dataio.harvester.types.RRHarvesterConfig', '{"includeRelations": true, "resource": "jdbc/dataio/rawrepo-cisterne", "format": "basis", "batchSize": 10000, "destination": "basis-cisterne", "consumerId": "basis-decentral", "enabled": true, "openAgencyTarget": {"url": "http://openagency.addi.dk/2.25/"}, "formatOverrides": {"870970": "basis"}, "id": "basis-sync-cisterne"}'::jsonb);
insert into harvester_configs (id, version , type, content ) values ( 12, 1, 'dk.dbc.dataio.harvester.types.RRHarvesterConfig', '{"includeRelations": true, "resource": "jdbc/dataio/rawrepo", "format": "katalog", "batchSize": 10000, "destination": "broend30", "consumerId": "broend30-sync", "enabled": true, "openAgencyTarget": {"url": "http://openagency.addi.dk/2.25/"}, "formatOverrides": {}, "type": "TEST", "id": "fbs-test-sync-broend30"}'::jsonb);
insert into harvester_configs (id, version , type, content ) values ( 13, 1, 'dk.dbc.dataio.harvester.types.RRHarvesterConfig', '{"includeRelations": true, "resource": "jdbc/dataio/rawrepo-cisterne", "format": "katalog", "batchSize": 10000, "destination": "broend-aqua", "consumerId": "broend30-sync", "enabled": true, "openAgencyTarget": {"url": "http://openagency.addi.dk/2.25/"}, "formatOverrides": {"870970": "basis"}, "type": "TRANSIENT", "id": "broend30-sync-cisterne"}'::jsonb);

insert into harvester_configs (id, version , type, content ) values ( 14, 1, 'dk.dbc.dataio.harvester.types.OLDRRHarvesterConfig', '{"includeRelations": true, "resource": "jdbc/dataio/rawrepo-cisterne", "format": "katalog", "batchSize": 10000, "destination": "broend-aqua", "consumerId": "broend30-sync", "enabled": true, "openAgencyTarget": {"url": "http://openagency.addi.dk/2.25/"}, "formatOverrides": {"870970": "basis"}, "type": "TRANSIENT", "id": "broend30-sync-cisterne"}'::jsonb);
