#!/bin/bash

JAR=""

case "$1" in
    "job-replicator")
        JAR=dataio-cli-job-replicator.jar
        ;;
    "acctest")
        JAR=dataio-cli-acctest.jar
        ;;
    *)
        echo "usage: $0 prog
            prog: [job-replicator|acctest]

            ex: $0 job-replicator -h"
        exit 1
        ;;
esac
shift

docker run -it --rm --user $(id -u):$(id -g) --volume="/etc/group:/etc/group:ro" --volume="/etc/passwd:/etc/passwd:ro" --volume="/etc/shadow:/etc/shadow:ro" docker-io.dbc.dk/dataio-cli:prod java -jar /usr/bin/"$JAR" "$@"
