package dk.dbc.dataio.jobstore.rest;

import dk.dbc.dataio.jobstore.ejb.JobsBean;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.ws.rs.ApplicationPath;
import javax.ws.rs.core.Application;
import java.util.HashSet;
import java.util.Set;

/**
 * This class defines the other classes that make up this JAX-RS application
 * by having the getClasses method return a specific set of resources.
 */
@ApplicationPath("/")
public class JobStoreApplication extends Application {
    private static final Logger log = LoggerFactory.getLogger(JobStoreApplication.class);

    @Override
    public Set<Class<?>> getClasses() {
        final Set<Class<?>> classes = new HashSet<>();
        classes.add(JobsBean.class);
        classes.add(JsonExceptionMapper.class);
        classes.add(ReferencedEntityNotFoundExceptionMapper.class);
        for (Class<?> clazz : classes) {
            log.info("Registered {} resource", clazz.getName());
        }
        return classes;
    }

    /**
     * Do not modify addRestResourceClasses() method.
     * It is automatically re-generated by NetBeans REST support to populate
     * given list with all resources defined in the project.
     */
    private void addRestResourceClasses(Set<Class<?>> resources) {
        resources.add(dk.dbc.dataio.jobstore.ejb.JobsBean.class);
        resources.add(dk.dbc.dataio.jobstore.rest.JsonExceptionMapper.class);
        resources.add(dk.dbc.dataio.jobstore.rest.ReferencedEntityNotFoundExceptionMapper.class);
    }
}
