#!/usr/bin/env bash
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PARALLEL_EXEC=$(which parallel)
if [ "${PARALLEL_EXEC}" != "" ] ; then
    echo "parallel build"
    find ${SCRIPT_DIR}/.. -name build_docker_image.sh | parallel --no-notice {}
else
    echo "sequential build"
    find ${SCRIPT_DIR}/.. -name build_docker_image.sh -exec echo test {} \;
fi
