version: '3'
networks:
  default:
    external:
       name: dataio-dev
#    driver: bridge
#    ipam:
#      driver: default
#      config:
#        - subnet: 10.0.8.0/28

services:
    filestore:
      image: dbc-payara-filestore-devel:latest
      depends_on:
        - "dbc-postgres-filestore"
      environment:
        - DBC_POSTGRES_FILESTORE_ENV_POSTGRES_DB=filestore
        - DBC_POSTGRES_FILESTORE_ENV_POSTGRES_PASSWORD=filestore
        - DBC_POSTGRES_FILESTORE_ENV_POSTGRES_USER=filestore
        - DBC_POSTGRES_FILESTORE_ENV_POSTGRES_SERVERNAME=dbc-postgres-filestore
        - LOGBACK_URL=https://svn.dbc.dk/repos/dataio/trunk/deploy/config/generic-logback-debug.xml
        - USE_JMX=1
      expose:
        - "8080"
        - "4848"
      ports:
        - "10100:8080"


    jobstore:
       image: dbc-payara-jobstore-devel:latest
       depends_on:
         - "dbc-postgres-jobstore"
         - "flowstore"
         - "filestore"
         - "dbc-openmq"
       environment:
        - DBC_POSTGRES_JOBSTORE_ENV_POSTGRES_DB=jobstore
        - DBC_POSTGRES_JOBSTORE_ENV_POSTGRES_PASSWORD=jobstore
        - DBC_POSTGRES_JOBSTORE_ENV_POSTGRES_USER=jobstore
        - LOGBACK_URL=https://svn.dbc.dk/repos/dataio/trunk/deploy/config/generic-logback-debug.xml
        - USE_JMX=1
        - DBC_MAIL_ENV_HOST=mail.dbc.dk
        - DBC_MAIL_ENV_USER=mailuser
        - DBC_MAIL_ENV_FROM=${USER}@dbc.dk
        - DBC_MAIL_ENV_TO_FALLBACK=${USER}@dbc.dk
        - FLOWSTORE_URL=http://flowstore:8080/dataio/flow-store-service
        - FILESTORE_URL=http://filestore:8080/dataio/file-store-service
        - OPENAGENCY_URL=http://openagency.addi.dk/2.28
        - MAX_HEAP_IN_GB=4
       expose:
         - "8080"
       ports:
         - "8188:8080"
         - "4188:4848"



    flowstore:
       image: dbc-payara-flowstore-devel:latest
       depends_on:
         - "dbc-postgres-flowstore"
       environment:
        - DBC_POSTGRES_FLOWSTORE_ENV_POSTGRES_DB=flowstore
        - DBC_POSTGRES_FLOWSTORE_ENV_POSTGRES_PASSWORD=flowstore
        - DBC_POSTGRES_FLOWSTORE_ENV_POSTGRES_USER=flowstore
        - LOGBACK_URL=https://svn.dbc.dk/repos/dataio/trunk/deploy/config/generic-logback-debug.xml
        - USH_HARVESTER_URL=http://dataio-ush-s01.dbc.dk:8080/harvester
       expose:
         - "8080"

    gui:
       image: dbc-payara-gui-devel:latest
       depends_on:
          - "filestore"
          - "jobstore"
          - "flowstore"
       environment:
        - LOGBACK_URL=https://svn.dbc.dk/repos/dataio/trunk/deploy/config/generic-logback-debug.xml
        #- ELK_URL=http://elk.dbc.dk:5601/#/discover/Traceid\:-Staging?_g\=(time\:(from\:now-7d,mode\:quick,to\:now))&_a\=(query\:(query_string\:(analyze_wildcard\:!t,query\:\\'%22@TRACEID@%22\\')),sort\\:!(\\'@timestamp\\',asc))
        - ELK_URL=hest
        - FTP_URL=dataio-be-s02/datain
        - USH_HARVESTER_URL=http://dataio-ush-s01.dbc.dk:8080/harvester
        - FILESTORE_URL=http://filestore:8080/dataio/file-store-service
        - FLOWSTORE_URL=http://flowstore:8080/dataio/flow-store-service
        - JOBSTORE_URL=http://jobstore:8080/dataio/job-store-service
        - LOGSTORE_URL=http://logstore:8080/dataio/log-store-service
        - SCM_URL=https://svn.dbc.dk/repos
        - URL_DATAIO_USH_SOLR_HARVESTER_RS=http://ush-harvester/dataio/harvester/ush-solr
        - USE_JMX=1
       ports:
        - "8088:8080"
        - "4088:4848"


    job-processor:
        image: dbc-payara-jobprocessor-devel
        depends_on:
          - "dbc-postgres-logstore"
          - "jobstore"
          - "flowstore"
          - "dbc-openmq"
        environment:
          - DBC_OPENMQ_ENV_MQ_PORT=7676
          - DBC_POSTGRES_LOGSTORE_ENV_POSTGRES_DB=logstore
          - DBC_POSTGRES_LOGSTORE_ENV_POSTGRES_PASSWORD=logstore
          - DBC_POSTGRES_LOGSTORE_ENV_POSTGRES_USER=logstore
          - FLOWSTORE_URL=http://flowstore:8080/dataio/flow-store-service
          - JOBSTORE_URL=http://jobstore:8080/dataio/job-store-service
          - LOGBACK_URL=https://svn.dbc.dk/repos/dataio/trunk/deploy/config/jobprocessor-logback-debug.xml
          - MAX_HEAP_IN_GB=4
          - OPENAGENCY_URL=http://openagency.addi.dk/2.30
          - PROCESSOR_SHARD=business
          - USE_JMX=1

    dummy-sink:
        image: dbc-payara-dummy-sink-devel
        depends_on:
           - "jobstore"
           - "flowstore"
           - "dbc-openmq"
        environment:
           - FLOWSTORE_URL=http://flowstore:8080k/dataio/flow-store-service
           - JOBSTORE_URL=http://jobstore:8080/dataio/job-store-service
           - LOGBACK_URL=https://svn.dbc.dk/repos/dataio/trunk/deploy/config/generic-logback-debug.xml
           - MAX_HEAP_IN_GB=2
           - OPENAGENCY_URL=http://openagency.addi.dk/2.30
           - USE_JMX=1

    logstore:
        image: dbc-payara-logstore-devel
        depends_on:
           - "dbc-postgres-logstore"
        environment:
           - DBC_POSTGRES_LOGSTORE_ENV_POSTGRES_DB=logstore
           - DBC_POSTGRES_LOGSTORE_ENV_POSTGRES_PASSWORD=logstore
           - DBC_POSTGRES_LOGSTORE_ENV_POSTGRES_USER=logstore
           - FLOWSTORE_URL=http://flowstore:8080/dataio/flow-store-service
           - JOBSTORE_URL=http://jobstore:8080/dataio/job-store-service
           - LOGBACK_URL=https://svn.dbc.dk/repos/dataio/trunk/deploy/config/generic-logback-debug.xml
           - MAX_HEAP_IN_GB=2
           - OPENAGENCY_URL=http://openagency.addi.dk/2.30
           - USE_JMX=1

#
#
# Support
    dbc-openmq:
       image: docker-os.dbc.dk/solr-indexer-cloud-mq:latest


#
#
# Databases
#

    dbc-postgres-filestore:
      image: docker.dbc.dk/dbc-postgres:latest

      environment:
       - POSTGRES_PASSWORD=filestore
       - POSTGRES_USER=filestore
       - POSTGRES_DB=filestore
      expose:
        - "5432"

    dbc-postgres-jobstore:
      image: docker.dbc.dk/dbc-postgres:latest

      environment:
       - POSTGRES_PASSWORD=jobstore
       - POSTGRES_USER=jobstore
       - POSTGRES_DB=jobstore

      expose:
        - "5432"
      ports:
        - "14132:5432"

    dbc-postgres-flowstore:
       image: docker.dbc.dk/dbc-postgres:latest

       environment:
         - POSTGRES_PASSWORD=flowstore
         - POSTGRES_USER=flowstore
         - POSTGRES_DB=flowstore
       expose:
          - "5432"


    dbc-postgres-logstore:
       image: docker.dbc.dk/dbc-postgres:latest

       environment:
         - POSTGRES_PASSWORD=logstore
         - POSTGRES_USER=logstore
         - POSTGRES_DB=logstore
       expose:
          - "5432"

