#!/usr/bin/env bash
PARALLEL_EXEC=$(which parallel)
if [ "${PARALLEL_EXEC}" != "" ] ; then
    echo "parallel rmi"
    docker images -qf dangling=true | parallel --no-notice --no-run-if-empty docker rmi {}
else
    if [[ "$OSTYPE" == "darwin" ]]; then
        docker images -qf dangling=true | xargs docker rmi
    else
        docker images -qf dangling=true | xargs --no-run-if-empt docker rmi
    fi
fi
