#!/bin/sh

set -x # echo on

basedir=$(dirname $0)
. $basedir/devel-base

$glassfish_home/bin/asadmin delete-jdbc-resource $filestore_resource
$glassfish_home/bin/asadmin delete-jdbc-connection-pool $filestore_pool_resource
$glassfish_home/bin/asadmin delete-custom-resource $logback_resource
