docker run -it \
  -e LOG_FORMAT=text \
  -e JAVA_MAX_HEAP_SIZE=2G \
  -e ARTEMIS_MQ_HOST=dataio-artemis-service.metascrum-staging.svc.cloud.dbc.dk \
  -e JOBSTORE_URL=http://localhost/dataio/job-store-service \
  -e MESSAGE_NAME_FILTER=dummy \
  -e FLOWSTORE_URL=http://dataio-flowstore-service.metascrum-staging.svc.cloud.dbc.dk/dataio/flow-store-service \
  -e FILESTORE_URL=http://dataio-filestore-service.metascrum-staging.svc.cloud.dbc.dk/dataio/file-store-service \
  -e LOGSTORE_URL=http://dataio-logstore-service.metascrum-staging.svc.cloud.dbc.dk/dataio/log-store-service/ \
  -e RAWREPO_HARVESTER_URL=http://dataio-rr-harvester-service.metascrum-staging.svc.cloud.dbc.dk/dataio/harvester/rr \
  -e TICKLE_REPO_HARVESTER_URL=http://dataio-tickle-harvester-service.metascrum-staging.svc.cloud.dbc.dk/dataio/harvester/tickle-repo \
  -e VIPCORE_ENDPOINT=http://vipcore.iscrum-vip-prod.svc.cloud.dbc.dk \
  -e JOBSTORE_DB_URL=db_user:db_password@192.168.0.88:5432/jobstore_db \
  -e MAIL_HOST=webmail.dbc.dk \
  -e MAIL_USER=mailuser \
  -e MAIL_FROM=danbib@kiska.dbc.dk \
  -e MAIL_TO_FALLBACK=bruges-ikke@dbc.dk \
  -e TZ=Europe/Copenhagen \
  -e ENABLE_REMOTE_DEBUGGING=yes \
  -p 4848:4848 \
  -p 9009:9009 \
  -p 8080:8080 \
  docker-metascrum.artifacts.dbccloud.dk/dbc-payara-jobstore:devel
