package dk.dbc.dataio.gui.client.pages.item.show;


import com.google.gwt.event.shared.HandlerRegistration;
import com.google.gwt.user.cellview.client.Column;
import com.google.gwt.user.cellview.client.TextColumn;
import com.google.gwt.view.client.Range;
import com.google.gwt.view.client.SelectionChangeEvent;
import com.google.gwt.view.client.SingleSelectionModel;
import dk.dbc.dataio.gui.client.model.DiagnosticModel;
import dk.dbc.dataio.gui.client.model.ItemModel;
import dk.dbc.dataio.gui.util.ClientFactory;

import java.util.List;


/**
 * This class is the View class for the Items Show View
 */
public class View extends ViewWidget {

    class Context {
        SingleSelectionModel<ItemModel> selectionModel = new SingleSelectionModel<>();
        HandlerRegistration handlerRegistration = null;
        ItemsListView listView;

        public Context(ItemsListView listView) {
            this.listView = listView;
        }
    }

    Context allContext = new Context(allItemsList);
    Context failedContext = new Context(failedItemsList);
    Context ignoredContext = new Context(ignoredItemsList);
    public AsyncItemViewDataProvider dataProvider;

    /**
     * Default constructor
     *
     * @param clientFactory, the client factory
     */
    public View(ClientFactory clientFactory) {
        super(clientFactory);
        dataProvider = new AsyncItemViewDataProvider(clientFactory,this);
        setupColumns(allItemsList);
        dataProvider.addDataDisplay(allItemsList.itemsTable);
        setupColumns(failedItemsList);
        dataProvider.addDataDisplay(failedItemsList.itemsTable);
        setupColumns(ignoredItemsList);
        dataProvider.addDataDisplay(ignoredItemsList.itemsTable);
        setupColumns(jobDiagnosticTabContent);
    }

    /*
     * Package scoped Constructor used for unit testing.
     */
    View(ClientFactory clientFactory, Boolean setupColumns) {
        super(clientFactory);

        dataProvider = new AsyncItemViewDataProvider(clientFactory, this);
        if(setupColumns) {
            setupColumns(allItemsList);
            setupColumns(failedItemsList);
            setupColumns(ignoredItemsList);
            setupColumns(jobDiagnosticTabContent);
        }
    }

    /**
     * Enables or disables one of the items table in the view
     * Thereby also enables or disables events from being generated by the selection
     * @param enable True: Selection is possible, false: Selection is not possible (and no events are triggered)
     * @param context The context (All, Failed or Ignored table)
     */
    public void enableSelection(boolean enable, Context context) {
        if (enable) {
            if (context.handlerRegistration == null) {
                context.handlerRegistration = context.selectionModel.addSelectionChangeHandler(new SelectionChangeHandlerClass(context));
            }
            context.listView.itemsTable.setSelectionModel(context.selectionModel);
        } else {
            if (context.handlerRegistration != null) {
                context.handlerRegistration.removeHandler();
                context.handlerRegistration = null;
            }
            context.listView.itemsTable.setSelectionModel(null);
        }
    }

    /**
     * Force a data refresh of the itemsTables belonging to allItemsList, failedItemsList, ignoredItemsList.
     */
    public void refreshItemsTable() {
        allItemsList.itemsTable.setVisibleRangeAndClearData(new Range(0, 20), true);
        failedItemsList.itemsTable.setVisibleRangeAndClearData(new Range(0, 20), true);
        ignoredItemsList.itemsTable.setVisibleRangeAndClearData(new Range(0, 20), true);
    }

    /**
     * Enables or disables all selections in all Items Tables
     * Thereby also enables or disables events from being generated by the selection
     * @param enable True: Selection is possible, false: Selection is not possible (and no events are triggered)
     */
    public void setSelectionEnabled(boolean enable) {
        enableSelection(enable, allContext);
        enableSelection(enable, failedContext);
        enableSelection(enable, ignoredContext);
    }

    public void setItemModels(ItemsListView listView, List<ItemModel> itemModels){
        presenter.setItemModels(listView, itemModels);
    }

    /**
     * Private methods
     */

    /**
     * This method sets up all columns in the view
     * It is called before data has been applied to the view - data is being applied in the setItems method
     */
    @SuppressWarnings("unchecked")
    void setupColumns(final ItemsListView listView) {
        listView.itemsTable.addColumn(constructItemColumn(), texts.column_Item());
        listView.itemsTable.addColumn(constructStatusColumn(), texts.column_Status());
        listView.itemsTable.setVisibleRange(0, 20);
        listView.itemsPager.setDisplay(listView.itemsTable);
    }

    @SuppressWarnings("unchecked")
    void setupColumns(final JobDiagnosticTabContent jobDiagnosticTabContent) {
        jobDiagnosticTabContent.jobDiagnosticTable.addColumn(constructDiagnosticLevelColumn(), texts.column_Level());
        jobDiagnosticTabContent.jobDiagnosticTable.addColumn(constructDiagnosticMessageColumn(), texts.column_Message());
    }

    Column constructDiagnosticLevelColumn() {
        return new TextColumn<DiagnosticModel>() {
            @Override
            public String getValue(DiagnosticModel model) {
                return model.getLevel();
            }
        };
    }

    Column constructDiagnosticMessageColumn() {
        return new TextColumn<DiagnosticModel>() {
            @Override
            public String getValue(DiagnosticModel model) {
                return model.getMessage();
            }
        };
    }


    /**
     * This method constructs the Item column
     * Should have been private, but is package-private to enable unit test
     *
     * @return the constructed Item column
     */
    Column constructItemColumn() {
        return new TextColumn<ItemModel>() {
            @Override
            public String getValue(ItemModel model) {
                return texts.text_Item() + " " + model.getItemNumber();
            }
        };
    }

    /**
     * This method constructs the Status column
     * Should have been private, but is package-private to enable unit test
     *
     * @return the constructed Status column
     */
    Column constructStatusColumn() {
        return new TextColumn<ItemModel>() {
            @Override
            public String getValue(ItemModel model) {
                return formatStatus(model.getStatus());
            }
        };
    }

    private String formatStatus(ItemModel.LifeCycle lifeCycle) {
        switch (lifeCycle) {
            case PARTITIONING:
                return texts.lifecycle_Partitioning();
            case PROCESSING:
                return texts.lifecycle_Processing();
            case DELIVERING:
                return texts.lifecycle_Delivering();
            case DONE:
                return texts.lifecycle_Done();
            default:
                return texts.lifecycle_Unknown();
        }
    }


    /*
     * Private classes
     */

    class SelectionChangeHandlerClass implements SelectionChangeEvent.Handler {
        private Context context;
        public SelectionChangeHandlerClass(Context context) {
            super();
            this.context = context;
        }
        public void onSelectionChange(SelectionChangeEvent event) {
            ItemModel selected = context.selectionModel.getSelectedObject();
            if (selected != null) {
                presenter.itemSelected(context.listView, selected);
            }
        }
    }

}
