CREATE TABLE LOGENTRY (
    ID                BIGSERIAL PRIMARY KEY,
    TIMESTAMP         TIMESTAMP NOT NULL,
    FORMATTED_MESSAGE TEXT,
    THREAD_NAME       TEXT,
    LOGGER_NAME       TEXT,
    LEVEL_STRING      TEXT,
    CALLER_FILENAME   TEXT,
    CALLER_CLASS      TEXT,
    CALLER_METHOD     TEXT,
    CALLER_LINE       TEXT,
    STACK_TRACE       TEXT,
    MDC               TEXT,
    JOB_ID            TEXT,
    CHUNK_ID          BIGINT,
    ITEM_ID           BIGINT
);

CREATE INDEX TIMESTAMP_IDX ON LOGENTRY(TIMESTAMP);
CREATE INDEX TRACKING_ID_IDX ON LOGENTRY(JOB_ID, CHUNK_ID, ITEM_ID);


