/*
 * DataIO - Data IO
 * Copyright (C) 2015 Dansk Bibliotekscenter a/s, Tempovej 7-11, DK-2750 Ballerup,
 * Denmark. CVR: 15149043
 *
 * This file is part of DataIO.
 *
 * DataIO is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * DataIO is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with DataIO.  If not, see <http://www.gnu.org/licenses/>.
 */

package dk.dbc.dataio.sink.es.entity.es;

import javax.persistence.Column;
import javax.persistence.Id;
import java.io.Serializable;
import java.math.BigInteger;

/**
 * Created by ja7 on 23-09-14.
 * AutoGenerated combined Primary Key for SuppliedRecordsClass
 */
public class SuppliedRecordsEntityPK implements Serializable {
    @Id
    @Column(name = "targetreference", nullable = false, insertable = true, updatable = true, precision = 0)
    public BigInteger targetreference;
    @Id
    @Column(name = "lbNr", nullable = false, insertable = true, updatable = true, precision = 0)
    public BigInteger lbnr;

    public SuppliedRecordsEntityPK(long tReference, long lbNr) {
        this.targetreference = BigInteger.valueOf(tReference);
        this.lbnr = BigInteger.valueOf(lbNr);

    }

    public SuppliedRecordsEntityPK() {
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        SuppliedRecordsEntityPK that = (SuppliedRecordsEntityPK) o;

        if (lbnr != null ? !lbnr.equals(that.lbnr) : that.lbnr != null) return false;
        if (targetreference != null ? !targetreference.equals(that.targetreference) : that.targetreference != null)
            return false;

        return true;
    }

    @Override
    public int hashCode() {
        int result = targetreference != null ? targetreference.hashCode() : 0;
        result = 31 * result + (lbnr != null ? lbnr.hashCode() : 0);
        return result;
    }
}
