#!/bin/sh

# This script gets records from basis based on the list of id's below
# and converts them to marcXchange and copies them to the testdata 
# input folder with harvester wrapping tags.

SUBMITTER=870970
#for RECORD in 51144104 45371565 45371581 45371603 45371611 45395936 45425673 45425665 49398441
for RECORD in 22725726
do

RECID="$SUBMITTER-basis_$RECORD"

# Make csv file

FAUST=$(echo "$RECORD"|sed 's/\([0-9]\{1\}\)\([0-9]\{3\}\)\([0-9]\{3\}\)\(.*\)/\"\1X\2X\3X\4\"/'|sed 's/X/ /g')

echo $RECID
echo $FAUST, "$SUBMITTER" > ~/dataio-testposter/csv/$RECID.id.csv

# Convert records
cd ~/datawell-convert/trunk/shell/

echo " - getting record from oracle"
./get_record_oracle "sebasis/sebasis@dora11.dbc.dk" < ~/dataio-testposter/csv/$RECID.id.csv > ~/dataio-testposter/txt/$RECID.txt
echo " - converting record to iso"
txt2marc ~/dataio-testposter/txt/$RECID.txt ~/dataio-testposter/iso/$RECID.iso

echo '<dataio-harvester-datafile><data-container><data-supplementary><creationDate>20140101</creationDate></data-supplementary><data>' >  ~/dataio-testposter/tmp1
echo " - converting record to marXchange"
./dm2ToMarcxchange "true" "sebasis/sebasis@dora11.dbc.dk" < ~/dataio-testposter/iso/$RECID.iso >  ~/dataio-testposter/tmp2
echo '</data></data-container></dataio-harvester-datafile>' >  ~/dataio-testposter//tmp3
cat  ~/dataio-testposter/tmp* |sed 's/<?xml version="1.0" encoding="UTF-8"?>//g'|sed -e :a -e '$!N;s/\n//;ta' -e 'P;D' > ~/dataio-testposter/xml/$RECID.xml

done
echo "... done"


