#!/bin/sh

# This script takes as input a file with marc records in iso2709 
# and converts them to marcXchange and adds them to the testdata/rr_harvester_output  
# folder with harvester wrapping tags.

if [ $# -ne 1 ]
then
    echo ""
    echo " USAGE: $0 <ISO-INPUT-FILE>"
    echo ""
    echo "This script converts marc records in ISO2709 to MarcXchange and wraps it in Raw Repo Harvester output xml"
    echo "If the iso file contains more than one record it will be split first and then each record will be processed"
    echo "The output is saved to ~/dataio-testdata/rr_harvester_output/"
    exit 1
fi

#DEFINE FUNCTION convert_record FIRST:
convert_record () {
        SINGLE_RECORD=$1
        PREFIX=$2
        #Get ID of record
        ID=$(semarc $SINGLE_RECORD | grep "001" | sed -e 's/\*/\n\*/g' | grep "\*a" | cut -d "a" -f2 | tr -d '[:space:]')
        echo $ID
        OUTPUTFILE=$PREFIX.$ID.xml

        # Convert records
        #cd ~/datawell-convert/trunk/shell/

        echo '<dataio-harvester-datafile><data-container><data-supplementary><creationDate>20140101</creationDate></data-supplementary><data>' >  ~/dataio-testdata/scripts/tmp/tmp1
        echo " - converting record to marXchange"
        ~/datawell-convert/trunk/shell/dm2ToMarcxchange "true" "sebasis/sebasis@dora11.dbc.dk" < $SINGLE_RECORD > ~/dataio-testdata/scripts/tmp/tmp2
        echo '</data></data-container></dataio-harvester-datafile>' > ~/dataio-testdata/scripts/tmp/tmp3
        cat  ~/dataio-testdata/scripts/tmp/tmp* |sed 's/<?xml version="1.0" encoding="UTF-8"?>//g'|sed -e :a -e '$!N;s/\n//;ta' -e 'P;D' | xmllint --format - > ~/dataio-testdata/rr_harvester_output/$OUTPUTFILE
	echo "output file added to ~/dataio-testdata/rr_harvester_output/$OUTPUTFILE"
        echo "" 
}

echo ""
echo "Input file: " $1

INPUT=$1
PREFIX=$(basename $INPUT | cut -c 1-6 )

#check for multiple records in iso file 
if [ $(cat $INPUT | spltmarc -c) -ne 1 ]
then 
    echo "Iso file contains" $(cat $INPUT | spltmarc -c) "records"
    echo "The input file will be split into individual records and processed from tmp dir"
    echo ""
    cd ~/dataio-testdata/scripts/tmp
    pwd
    rm *
    cat $INPUT | spltmarc -s 1 -f $PREFIX.
    for file in *
    do
	file_path=$(pwd)/$file
	echo "Input record: $file_path"
	convert_record $file_path $PREFIX
    done 

else
    echo "iso file has one record"
    echo "Input record: $INPUT"
    convert_record $INPUT $PREFIX
fi

cd ~/dataio-testdata/scripts/
