#!/bin/sh

set -x # echo on

basedir=$(dirname $0)
. $basedir/devel-base

$glassfish_home/bin/asadmin delete-jdbc-resource $rawrepo_resource
$glassfish_home/bin/asadmin delete-jdbc-connection-pool $rawrepo_pool_resource
$glassfish_home/bin/asadmin delete-custom-resource $filestore_endpoint_resource
$glassfish_home/bin/asadmin delete-custom-resource $logback_resource
