[template]
src = "db-connection-pools.xml.tmpl"
dest = "/home/gfish/dbc-glassfish.d/19-db-connection-pools.xml"

keys = [
    "/dbc/postgres/ticklerepo/env/postgres/user",
    "/dbc/postgres/ticklerepo/env/postgres/password",
    "/dbc/postgres/ticklerepo/env/postgres/servername",
    "/dbc/postgres/ticklerepo/env/postgres/db"
]
