package dk.dbc.dataio.sink.es.entity.es;

import javax.persistence.Column;
import javax.persistence.Id;
import java.io.Serializable;

/**
 * Created by ja7 on 23-09-14.
 * AutoGenerated combined Primary Key for SuppliedRecordsClass
 */
public class SuppliedRecordsEntityPK implements Serializable {
    @Id
    @Column(name = "targetreference", nullable = false, insertable = true, updatable = true, precision = 0)
    public Integer targetreference;
    @Id
    @Column(name = "lbnr", nullable = false, insertable = true, updatable = true, precision = 0)
    public Integer lbnr;

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        SuppliedRecordsEntityPK that = (SuppliedRecordsEntityPK) o;

        if (lbnr != null ? !lbnr.equals(that.lbnr) : that.lbnr != null) return false;
        if (targetreference != null ? !targetreference.equals(that.targetreference) : that.targetreference != null)
            return false;

        return true;
    }

    @Override
    public int hashCode() {
        int result = targetreference != null ? targetreference.hashCode() : 0;
        result = 31 * result + (lbnr != null ? lbnr.hashCode() : 0);
        return result;
    }
}
